import 'dart:convert';

const int sourceStringsVersion = 12;

final Map<String, String> sourceStrings = Map.unmodifiable(
  (json.decode(_sourceJson) as Map<String, dynamic>)
      .map((k, v) => MapEntry(k, v.toString())),
);

const _sourceJson = r'''
{
  "appTitle": "Plataforma de Badges Softinsa",
  "evolutionHello": "Olá",
  "savedBadgesTitle": "Badges Guardados",
  "savedBadgesEmptyTitle": "Nenhum badge guardado",
  "savedBadgesEmptySubtitle": "Guarde badges para os encontrar facilmente mais tarde.",
  "notificationsScreenTitle": "As suas notificações",
  "notificationsMarkAllShort": "Marcar todas",
  "notificationsFilterAll": "Todas",
  "notificationsTabRecent": "Recentes",
  "notificationsTabAll": "Todas",
  "notificationsEmpty": "Sem notificações para apresentar.",
  "termsScreenTitle": "Termos e Condições",
  "termsSection1Title": "1. Aceitação dos Termos",
  "termsSection1Body": "Ao aceder e utilizar a plataforma Softinsa Badge Platform, o utilizador concorda em cumprir os presentes Termos e Condições. Caso não concorde com alguma das condições aqui descritas, não deverá utilizar a plataforma.",
  "termsSection2Title": "2. Descrição do Serviço",
  "termsSection2Body": "A Softinsa Badge Platform é um sistema de credenciais digitais que permite aos consultores da Softinsa acompanhar, validar e partilhar as suas competências e certificações tecnológicas através de Learning Paths, Service Lines e Áreas.",
  "termsSection3Title": "3. Registo e Conta",
  "termsSection3Body": "O utilizador é responsável por manter a confidencialidade das suas credenciais de acesso. Qualquer atividade realizada na conta é da responsabilidade do titular. É proibida a partilha de credenciais com terceiros.",
  "termsSection4Title": "4. Utilização da Plataforma",
  "termsSection4Body": "A plataforma destina-se exclusivamente a uso profissional no âmbito das atividades da Softinsa. O utilizador compromete-se a não utilizar a plataforma para fins ilícitos, não carregar conteúdos ofensivos ou inadequados e a respeitar a propriedade intelectual de todos os materiais disponibilizados.",
  "termsSection5Title": "5. Badges e Certificações",
  "termsSection5Body": "Os badges obtidos representam competências validadas pela Softinsa. Os pontos acumulados são permanentemente preservados no perfil do consultor, mesmo que o badge atinja a data de expiração. Cada credencial obtida gera um URL público único para verificação externa.",
  "termsSection6Title": "6. Proteção de Dados (RGPD)",
  "termsSection6Body": "A Softinsa compromete-se a proteger os dados pessoais dos utilizadores em conformidade com o Regulamento Geral de Proteção de Dados (RGPD). Os dados recolhidos são utilizados exclusivamente para o funcionamento da plataforma e não serão partilhados com terceiros sem o consentimento prévio do utilizador, exceto quando exigido por lei.",
  "termsSection7Title": "7. Propriedade Intelectual",
  "termsSection7Body": "Todos os conteúdos, logótipos, design e funcionalidades da plataforma são propriedade da Softinsa. A reprodução, distribuição ou modificação de qualquer conteúdo sem autorização prévia é estritamente proibida.",
  "termsSection8Title": "8. Alterações aos Termos",
  "termsSection8Body": "A Softinsa reserva-se o direito de modificar os presentes Termos e Condições a qualquer momento. Os utilizadores serão notificados de alterações significativas através da plataforma.",
  "termsSection9Title": "9. Contacto",
  "termsSection9Body": "Para questões relacionadas com estes termos, contacte a equipa de suporte da Softinsa através dos canais internos disponíveis na plataforma.",
  "termsLastUpdate": "Última atualização: maio de 2026",
  "loading": "A carregar...",
  "back": "Voltar",
  "tryAgain": "Tentar novamente",
  "submit": "Submeter",
  "area": "Área",
  "level": "Nível",
  "date": "Data",
  "points": "Pontos",
  "description": "Descrição",
  "skills": "Competências",
  "requirements": "Requisitos",
  "notes": "Observações",
  "openLink": "Abrir ligação",
  "removeFile": "Remover ficheiro",
  "screenNotAvailable": "Ecrã ainda não disponível.",
  "welcomeBack": "Bem-vindo de volta",
  "loginSubtitle": "Introduz as tuas credenciais para continuar.",
  "emailOrUsername": "Email ou username",
  "emailOrUsernameHint": "Introduz o teu email ou username",
  "emailOrUsernameRequired": "Email ou username é obrigatório.",
  "usernameMinChars": "O username deve ter pelo menos 3 caracteres.",
  "password": "Password",
  "enterPasswordHint": "Introduz a tua password",
  "saveLoginData": "Guardar sessão",
  "forgotPassword": "Esqueceste a password?",
  "login": "Entrar",
  "noAccount": "Não tens conta?",
  "register": "Registar",
  "loginSuccess": "Bem-vindo de volta, {user}!",
  "loginErrorInvalidCredentials": "Erro no login. Verifica as credenciais.",
  "loginErrorServer": "Erro ao ligar ao servidor.",
  "createAccount": "Criar conta",
  "registerTitle": "Cria a tua conta",
  "registerSubtitle": "Preenche os dados para criares a tua conta.",
  "name": "Nome",
  "nameHint": "João Silva",
  "username": "Username",
  "usernameHint": "joaosilva",
  "email": "Email",
  "emailHint": "teu.email@softinsa.com",
  "createPasswordHint": "Cria uma password segura",
  "confirmPassword": "Confirmar password",
  "confirmPasswordHint": "Confirma a tua password",
  "optionalFields": "Campos opcionais",
  "phone": "Telefone",
  "phoneHint": "912 345 678",
  "invalidPhone": "Número de telefone inválido.",
  "birthdate": "Data de nascimento",
  "birthdateHint": "DD/MM/YYYY",
  "profileImage": "Imagem de perfil",
  "noFileSelected": "Nenhum ficheiro selecionado",
  "imageSelected": "Imagem selecionada",
  "imageUploadFailed": "Falha ao carregar a imagem para o servidor.",
  "pickFromPhone": "Escolher do telemóvel",
  "location": "Localização",
  "selectLocation": "Selecionar localização",
  "preferredLanguageOptional": "Idioma preferido (opcional)",
  "selectLanguage": "Selecionar idioma",
  "aboutMe": "Sobre mim",
  "aboutMeHint": "Conta um pouco sobre o teu percurso, objetivos e interesses.",
  "acceptTermsPrefix": "Aceito os ",
  "termsAndConditions": "termos e condições",
  "andThe": " e a ",
  "privacyPolicy": "política de privacidade",
  "mustAcceptTerms": "Tens de aceitar os termos e condições.",
  "finishRegister": "Concluir registo",
  "alreadyHaveAccount": "Já tens conta?",
  "doLogin": "Iniciar sessão",
  "passwordsDoNotMatch": "As passwords não coincidem.",
  "selectAreasDescription": "Escolhe até 5 áreas de especialização e marca a tua área principal.",
  "maxFiveAreas": "Podes selecionar no máximo 5 áreas.",
  "areasLoadFailed": "Falha ao carregar áreas: {error}",
  "noAreasAvailable": "Sem áreas disponíveis.",
  "areasEditHint": "A primeira área selecionada é a principal. Mínimo 1, máximo 5.",
  "areasMinRequired": "Tens de selecionar pelo menos 1 área.",
  "areas": "Áreas",
  "confirmRegister": "Confirmar registo",
  "registerSummary": "Resumo do registo",
  "personalData": "Dados pessoais",
  "notFilled": "Não preenchido",
  "notFilledF": "Não preenchida",
  "selectedAreas": "Áreas selecionadas",
  "mainArea": "Área principal",
  "notDefined": "Não definido",
  "noneSelectedArea": "Nenhuma área selecionada.",
  "chooseAreasTitle": "Escolher áreas",
  "chooseAreasMenuLabel": "Escolher áreas",
  "chooseAreasMainSectionTitle": "Áreas selecionadas",
  "chooseAreasMainHint": "Toque numa área selecionada para a definir como principal.",
  "chooseAreasNoneSelected": "Ainda não selecionou nenhuma área.",
  "chooseAreasAvailableTitle": "Áreas disponíveis",
  "chooseAreasChooseHint": "Escolha entre 1 e 5 áreas para o seu perfil.",
  "chooseAreasConfirm": "Confirmar as minhas áreas.",
  "chooseAreasSavedSuccess": "Áreas atualizadas com sucesso.",
  "chooseAreasSaveError": "Não foi possível atualizar as áreas.",
  "registerUser": "Registar utilizador",
  "userRegisteredSuccess": "Utilizador {username} registado com sucesso!",
  "registerErrorInvalidData": "Erro ao registar utilizador. Verifica os dados.",
  "unexpectedError": "Ocorreu um erro inesperado: {error}",
  "recoverPassword": "Recuperar password",
  "recoverSubtitle": "Introduz o teu email para receberes instruções de recuperação.",
  "sendInstructions": "Enviar instruções",
  "emailSentTo": "Instruções enviadas para {email}",
  "emailSent": "Email enviado!",
  "checkMailbox": "Verifica a tua caixa de correio e segue as instruções.",
  "backToLogin": "Voltar ao login",
  "didNotReceiveEmail": "Não recebeste o email?",
  "checkSpam": "Verifica também a pasta de spam.",
  "dashboardGreeting": "Boa tarde, {name}!",
  "recentSubmissions": "Submissões recentes",
  "forYou": "Para ti",
  "keepGoing": "Continua assim!",
  "dashboardTopPercentPrefix": "Estás no top ",
  "dashboardTopPercentMiddle": " dos que mais ",
  "dashboardTopPercentHighlight": "badges conquistaram",
  "dashboardTopPercentSuffix": " na última semana.",
  "dashboardAreaLowCode": "LowCode",
  "dashboardAreaDevSecOps": "DevSecOps",
  "dashboardAreaUxUi": "Design UX/UI",
  "dashboardAreaAutomation": "Automação",
  "submissionStatusInReview": "Em avaliação",
  "submissionStatusRejected": "Rejeitado",
  "submissionStatusApproved": "Aprovado",
  "statistics": "Estatísticas",
  "completedBadges": "Badges concluídos",
  "areasWithCertifications": "Áreas com\ncertificações",
  "totalBadges": "Total de badges",
  "certificationsByArea": "Certificações por área",
  "noBadgesYet": "Sem badges ainda",
  "monthApril": "Abril",
  "monthMay": "Maio",
  "monthJune": "Junho",
  "monthJuly": "Julho",
  "monthAugust": "Agosto",
  "navExplore": "Explorar",
  "navBadges": "Badges",
  "navHome": "Início",
  "navProgress": "Evolução",
  "navProfile": "Perfil",
  "exploreCompetenciesTitle": "Explora novas competências",
  "searchBadgeHint": "Procura o teu badge",
  "noBadgesAvailable": "Sem badges disponíveis.",
  "filtersAndSorting": "Filtros e ordenação",
  "sortBy": "Ordenar por",
  "sortMostRecent": "Mais recentes",
  "sortOldest": "Mais antigos",
  "sortMostPoints": "Mais pontos",
  "areaFrontend": "Frontend",
  "areaBackend": "Backend",
  "areaFullstack": "Fullstack",
  "areaAi": "AI",
  "levelBeginner": "Iniciante",
  "levelIntermediate": "Intermédio",
  "levelExpert": "Expert",
  "badgeType": "Tipo de badge",
  "badgeTypeNormal": "Normal",
  "badgeTypeSpecial": "Especial",
  "last7Days": "Últimos 7 dias",
  "last30Days": "Últimos 30 dias",
  "thisYear": "Este ano",
  "overviewTab": "Visão geral",
  "detailsTab": "Detalhes",
  "submitApplication": "Submeter candidatura",
  "applicationTitle": "Candidatura",
  "applicationSectionBadge": "Badge selecionado",
  "applicationSectionEvidence": "Enviar evidências",
  "applicationSectionTerms": "Termos e condições",
  "applicationSectionSubmission": "Submissão",
  "applicationAttachFile": "Anexar ficheiro",
  "applicationAttachedFileSubtitle": "Associado a todos os requisitos da badge",
  "noRequirementsLinked": "Sem requisito associado.",
  "applicationSubmissionDisclaimer": "Ao submeter esta candidatura, confirmas que as evidências são verdadeiras e autorizas a validação pela equipa responsável.",
  "applicationStatusTitle": "Estado da candidatura",
  "applicationStatusForBadge": "Candidatura ao badge \"{badge}\"",
  "latestUpdates": "Últimas atualizações",
  "applicationInReviewBySll": "Em revisão pelo Service Line Leader",
  "applicationStatusTimestamp": "01/11/2025 às 17:23",
  "talentManagerLabel": "Talent Manager",
  "applicationStatusPlaceholderNote": "Estamos a validar as evidências submetidas e a confirmar o alinhamento com os requisitos da badge.",
  "attachedFiles": "Ficheiros anexados",
  "similarBadges": "Badges semelhantes",
  "badgeInfo": "Informações sobre o badge",
  "stepSubmitted": "Enviado",
  "stepTm": "TM",
  "stepServiceLineLeader": "Service Line Leader",
  "validationNameRequired": "Nome é obrigatório.",
  "validationNameMinChars": "O nome deve ter pelo menos 2 caracteres.",
  "validationUsernameRequired": "Username é obrigatório.",
  "validationUsernameMinChars": "O username deve ter pelo menos 3 caracteres.",
  "validationUsernameInvalidChars": "O username só pode conter letras, números, pontos e underscores.",
  "validationEmailRequired": "Email é obrigatório.",
  "validationEmailInvalidFormat": "Formato de email inválido.",
  "validationPasswordRequired": "Password é obrigatória.",
  "validationPasswordMinChars": "A password deve ter pelo menos 8 caracteres.",
  "validationPasswordConfirmRequired": "Confirma a password.",
  "validationPasswordConfirmMismatch": "As passwords não coincidem.",
  "validationBirthdateFormat": "A data deve estar no formato dd/mm/yyyy.",
  "validationBiographyMaxChars": "A biografia deve ter no máximo 1000 caracteres.",
  "monthJanuary": "Janeiro",
  "monthFebruary": "Fevereiro",
  "monthMarch": "Março",
  "monthSeptember": "Setembro",
  "monthOctober": "Outubro",
  "monthNovember": "Novembro",
  "monthDecember": "Dezembro",
  "monthShortJan": "Jan",
  "monthShortFeb": "Fev",
  "monthShortMar": "Mar",
  "monthShortApr": "Abr",
  "monthShortMay": "Mai",
  "monthShortJun": "Jun",
  "monthShortJul": "Jul",
  "monthShortAug": "Ago",
  "monthShortSep": "Set",
  "monthShortOct": "Out",
  "monthShortNov": "Nov",
  "monthShortDec": "Dez",
  "editProfile": "Editar Perfil",
  "fullName": "Nome completo",
  "biography": "Biografia",
  "biographyHint": "Escreva algo sobre si...",
  "selectLocationLabel": "Selecionar localização",
  "saveChanges": "Guardar Alterações",
  "profileUpdatedSuccess": "Perfil atualizado com sucesso.",
  "profileUpdateError": "Erro ao atualizar perfil.",
  "pointsTitle": "Pontos",
  "pointsLabel": "pontos",
  "history": "Histórico",
  "noPointsHistory": "Sem histórico de pontos.",
  "topPercentMessage": "Está no top {percent}% dos nossos consultores!",
  "seeMore": "Ver mais",
  "seeLess": "Ver menos",
  "weeklyPoints": "Pontos esta semana",
  "monthlyPoints": "Pontos por mês",
  "noDataAvailable": "Sem dados disponíveis.",
  "badgesEarned": "badges conquistados",
  "selectLanguageTitle": "Selecionar idioma",
  "usernameUnavailable": "Username indisponível.",
  "usernameMinCharsEdit": "Mínimo de 3 caracteres.",
  "nameRequired": "O nome é obrigatório.",
  "languageLabel": "Idioma",
  "goodMorning": "Bom dia",
  "goodAfternoon": "Boa tarde",
  "goodEvening": "Boa noite",
  "pwReqMinChars": "Mínimo de 8 caracteres",
  "pwReqUppercase": "Pelo menos 1 letra maiúscula",
  "pwReqLowercase": "Pelo menos 1 letra minúscula",
  "pwReqNumber": "Pelo menos 1 número",
  "pwReqSpecialChar": "Pelo menos 1 carácter especial (!@#$%^&*)",
  "loginErrorUserNotFound": "Utilizador ou email não encontrado.",
  "loginErrorWrongPassword": "Password incorreta.",
  "loginErrorAccountDeactivated": "A sua conta foi desativada. Contacte o administrador.",
  "loginErrorAccountLocked": "Conta bloqueada por tentativas excessivas. Tente novamente em 15 minutos.",
  "rejectedByTM": "Rejeitado pelo Talent Manager",
  "rejectedBySL": "Rejeitado pelo Service Line Leader",
  "fileTooLarge": "O ficheiro é demasiado grande. O tamanho máximo permitido é {size} MB.",
  "fileUploadError": "Não foi possível enviar o ficheiro. Tenta novamente.",
  "downloadingFile": "A transferir ficheiro...",
  "fileDownloaded": "Ficheiro transferido com sucesso.",
  "fileDownloadError": "Não foi possível transferir o ficheiro.",
  "openingLink": "A abrir ligação...",
  "certifiedCompetences": "Competências Certificadas",
  "competenceCount_one": "competência",
  "competenceCount_other": "competências",
  "celebrationFirstBadgeTitle": "Primeiro Badge!",
  "celebrationFirstBadgeDesc": "Parabéns! Conquistaste o teu primeiro badge. A tua jornada de certificações começou!",
  "celebration5BadgesTitle": "Estrela em Ascensão!",
  "celebration5BadgesDesc": "Incrível! Já conquistaste 5 badges. Estás a construir um portfólio impressionante!",
  "celebration10BadgesTitle": "Colecionador de Badges!",
  "celebration10BadgesDesc": "10 badges conquistados! A tua dedicação está a dar frutos. Continua assim!",
  "celebration25BadgesTitle": "Especialista!",
  "celebration25BadgesDesc": "25 badges! És uma referência na equipa. O teu empenho é inspirador!",
  "celebration50BadgesTitle": "Mestre dos Badges!",
  "celebration50BadgesDesc": "50 badges! Uma conquista extraordinária. És um verdadeiro especialista da Softinsa!",
  "modelDownloadFailed": "Não foi possível transferir o modelo de tradução. Verifica a ligação à internet.",
  "tabEarnedBadges": "Badges Obtidos",
  "tabApplications": "Candidaturas",
  "myBadgesSearchHint": "Procure badges",
  "applicationsSearchHint": "Procure candidaturas, badges",
  "noBadgesFound": "Nenhum badge encontrado.",
  "noEarnedBadgesYet": "Ainda não obteve nenhum badge.",
  "noApplicationsFound": "Nenhuma candidatura encontrada.",
  "applicationsLoadFailedLocal": "Não foi possível carregar candidaturas. A mostrar dados locais.",
  "filterAll": "Todos",
  "filterApproved": "Aprovadas",
  "filterInReview": "Em análise",
  "filterRejected": "Rejeitadas",
  "stateApproved": "Aprovado",
  "stateRejected": "Rejeitado",
  "stateInValidation": "Em validação",
  "proofDocument": "Comprovativo",
  "share": "Partilhar",
  "special": "Especial",
  "expiresOn": "Expira em",
  "badgeSharedSuccess": "Badge partilhado com sucesso!",
  "couldNotOpenLink": "Não foi possível abrir a ligação.",
  "couldNotIdentifyApplication": "Não foi possível identificar a candidatura associada a este badge.",
  "downloadingProof": "A transferir comprovativo...",
  "proofDownloadError": "Erro ao transferir comprovativo.",
  "gdprConsentError": "Não foi possível registar o consentimento RGPD. Tente novamente.",
  "approvedToday": "Aprovado hoje",
  "approvedOneDayAgo": "Aprovado há 1 dia",
  "approvedDaysAgo": "Aprovado há {days} dias",
  "shortTimeAgo": "há pouco tempo",
  "minutesAgo": "há {minutes} minutos",
  "hoursAgo": "há {hours} horas",
  "daysAgo": "há {days} dias",
  "consultantFallback": "Consultor",
  "userFallback": "Utilizador",
  "primaryAreaNotDefined": "Área principal não definida",
  "technicalJourney": "Jornada Técnica",
  "badgesMetric": "Badges",
  "skillsMetric": "Competências",
  "badgeGalleryTitle": "Galeria de Badges",
  "badgeGallerySubtitle": "Ver e gerir os seus badges de conquista",
  "viewGallery": "Ver galeria",
  "settings": "Definições",
  "myCharacteristics": "As minhas características",
  "notificationPreferences": "Preferências de notificações",
  "changePasswordAction": "Alterar palavra-passe",
  "emailSignature": "Assinatura de email",
  "languageChangeError": "Erro ao alterar idioma.",
  "helpAndPolicies": "Ajuda e políticas",
  "privacyPolicies": "Políticas de privacidade",
  "termsAndConditionsTitle": "Termos e condições",
  "help": "Ajuda",
  "logout": "Terminar sessão",
  "appVersion": "Versão {version}",
  "activeBadgesCount": "{count} ativos",
  "noEvolutionData": "Sem dados de evolução.",
  "badgesByYear": "Badges por ano",
  "evolutionGreeting": "Olá, {name}!",
  "badgesObtained": "Badges obtidos",
  "activeAchievements": "Conquistas ativas",
  "levelsCompleted": "Níveis concluídos",
  "totalPoints": "Pontos totais",
  "periodWeekly": "Semanal",
  "periodMonthly": "Mensal",
  "periodYearly": "Anual",
  "recentActivity": "Atividade recente",
  "timeAgoValue": "Há {time}",
  "applications": "Candidaturas",
  "approvalPercentage": "Percentagem de aprovação",
  "submittedApplications": "Candidaturas efetuadas",
  "learningPathProgress": "Progresso por Learning Path",
  "badgesPerArea": "Badges por área",

  "helpQuestionTitle": "Como posso ajudá-lo?",
  "helpQuestionSubtitle": "Explore as funcionalidades da aplicação e saiba como tirar o melhor partido da plataforma.",
  "helpFeatures": "Funcionalidades",
  "helpDashboardTitle": "Dashboard",
  "helpDashboardDesc": "O Dashboard é a sua página inicial. Aqui pode ver um resumo das suas atividades, anúncios recentes, o seu progresso e ranking geral da plataforma.",
  "helpExploreTitle": "Explorar Competências",
  "helpExploreDesc": "Nesta secção pode navegar por todos os badges disponíveis na plataforma. Utilize os filtros para pesquisar por área, nível, pontos ou data. Toque num badge para ver os detalhes e iniciar uma candidatura.",
  "helpMyBadgesTitle": "Os Meus Badges",
  "helpMyBadgesDesc": "Consulte os badges que já obteve no separador \"Badges Obtidos\" e acompanhe o estado das suas candidaturas no separador \"Candidaturas\". Pode partilhar ou transferir badges obtidos.",
  "helpEvolutionTitle": "Evolução",
  "helpEvolutionDesc": "A secção de Evolução mostra o seu progresso ao longo do tempo: pontos acumulados, badges conquistados e a sua posição no ranking. Acompanhe o crescimento da sua jornada técnica.",
  "helpProfileTitle": "Perfil",
  "helpProfileDesc": "No seu perfil pode ver e editar as suas informações pessoais, alterar o idioma da aplicação, consultar as suas características, gerir a assinatura de email e aceder às definições da conta.",
  "helpApplicationsTitle": "Candidaturas",
  "helpApplicationsDesc": "Para obter um badge, inicie uma candidatura na página de detalhes do badge. Anexe as evidências necessárias (ficheiros, certificados) e submeta. A candidatura será avaliada pelo Talent Manager e depois pelo Service Line Leader.",
  "helpNotificationsTitle": "Notificações",
  "helpNotificationsDesc": "Receba alertas sobre o estado das suas candidaturas, badges a expirar, e outras atualizações relevantes. Pode marcar notificações como lidas individualmente ou todas de uma vez.",
  "helpShareTitle": "Partilha de Badges",
  "helpShareDesc": "Após obter um badge, pode partilhá-lo publicamente. Na primeira partilha será pedido o consentimento GDPR. Os badges partilhados ficam acessíveis através de um link público de verificação.",

  "iAmIntro": "Eu {name} sou",
  "noCharacteristicsDefined": "Ainda sem características definidas.",

  "selectBadgesToShow": "Selecione os Badges a mostrar",
  "recentFilter": "Recentes",
  "previewLabel": "Pré-visualização",
  "previewBefore": "Antes",
  "previewAfter": "Depois",
  "noBadgeSelected": "Nenhum badge selecionado",
  "confirmEmailSignatureAction": "Confirmar Assinatura de email",
  "saveAndSendSignature": "Guardar e enviar a sua assinatura",
  "selectAtLeastOneBadge": "Selecione pelo menos um badge.",
  "emailSignatureSaved": "Assinatura de email guardada com sucesso.",
  "emailSignatureSaveError": "Erro ao guardar a assinatura de email.",

  "welcomeFirstLogin": "Bem-vindo!",
  "firstLoginPasswordPrompt": "Por segurança, defina uma nova password para a sua conta.",
  "currentPassword": "Password atual",
  "newPassword": "Nova password",
  "enterCurrentPassword": "Introduza a password atual.",
  "changePasswordButton": "Alterar Password",
  "changePasswordSuccess": "Password alterada com sucesso.",
  "changePasswordErrorGeneric": "Erro ao alterar password.",
  "errorCurrentPasswordWrong": "A password atual está incorreta. Verifique e tente novamente.",
  "errorPasswordFormatInvalid": "A nova password não cumpre os requisitos de segurança.",
  "errorPasswordSameAsCurrent": "A nova password não pode ser igual à password atual.",

  "applicationStartError": "Erro ao iniciar candidatura.",
  "applicationExistsInState": "Já existe uma candidatura em estado \"{state}\" para este badge.",
  "applicationGuidError": "Erro: GUID da candidatura não recebido.",
  "applicationSubmitError": "Erro ao submeter candidatura.",
  "submitting": "A submeter...",

  "applicationSubmitted": "Candidatura submetida",
  "applicationReceivedSuccess": "A sua candidatura foi recebida com sucesso!",
  "badgeTypeLabel": "Tipo de Badge",
  "submittedAtLabel": "Submetida a",
  "confirmationSentTo": "Confirmação enviada para",
  "nextSteps": "Próximos passos",
  "nextStepEvaluation": "Candidatura será avaliada",
  "nextStepResult": "Receberá um resultado em cerca de 5 dias",
  "viewApplicationStatus": "Ver estado da candidatura",
  "backToMenu": "Voltar ao Menu",

  "confirmYourApplication": "Confirme a sua candidatura",
  "applicationSubmittedSuccess": "A sua candidatura foi submetida com sucesso!",
  "sendConfirmationInstruction": "Para finalizar, envie o email de confirmação da sua candidatura para a badge:",
  "sending": "A enviar...",
  "sendConfirmationEmail": "Enviar email de confirmação",
  "emailResendUnavailable": "O reenvio de email não está disponível de momento. O email original foi enviado com a submissão.",
  "emailSendError": "Erro ao enviar email de confirmação.",
  "emailResendFailed": "Não foi possível reenviar o email. Tente novamente mais tarde.",
  "confirmationEmailSentTo": "Enviámos um email de confirmação para:",
  "applicationWillBeEvaluated": "A sua candidatura será avaliada pelo Talent Manager e pelo Service Line Leader. Receberá uma notificação com o resultado.",
  "resendEmailCooldown": "Reenviar email ({seconds} s)",
  "resendEmail": "Reenviar email",
  "emailNotReceived": "Não recebeu o email? Verifique a sua pasta de spam ou tente reenviar.",

  "applicationApprovedSuccess": "Candidatura aprovada com sucesso!",
  "inReviewBySLL": "Em revisão pelo Service Line Leader",
  "inReviewByTM": "Em revisão pelo Talent Manager",
  "applicationOpen": "Candidatura em aberto",
  "progress": "Progresso",
  "stepSubmittedLabel": "Submetido",
  "stepApprovedLabel": "Aprovado",
  "details": "Detalhes",
  "openedAt": "Aberta a",
  "observation": "Observação",
  "badgeInformation": "Informação do badge",
  "createdAt": "Criado a",
  "validityDays": "Validade: {days} dias",
  "applicationDetails": "Detalhes da candidatura",
  "applicationSubmittedDialog": "Candidatura submetida!",
  "applicationSubmittedDialogDesc": "A sua candidatura foi submetida com sucesso e será avaliada em breve.",
  "viewApplication": "Ver candidatura",
  "viewBadges": "Ver badges",

  "stateApprovedF": "Aprovada",
  "stateRejectedF": "Rejeitada",
  "stateInValidationF": "Em validação",
  "stateSubmittedF": "Submetida",
  "stateInAnalysis": "Em análise",
  "badgeSaved": "Badge guardado!",
  "badgeUnsaved": "Badge removido dos guardados.",
  "linkCopied": "Link copiado para a área de transferência!",
  "estimatedDuration": "Tempo estimado",
  "duration": "Duração",
  "validity": "Validade",
  "validityDays": "{days} dias",
  "markAsRead": "Marcar como lida",
  "timeNow": "Agora",
  "notifTypeHome": "Início",
  "notifTypeBadges": "Badges",
  "notifTypeApplications": "Candidaturas",
  "notifTypeAchievements": "Conquistas",
  "notifTypePoints": "Pontos",
  "notifTypeObjectives": "Objetivos",
  "notifTypeEvolution": "Evolução",
  "notifTypeAnnouncements": "Anúncios",
  "notifTypeSystem": "Sistema",
  "notifApplicationSubmitted": "Candidatura Submetida",
  "notifApprovedByTm": "Aprovado pelo Talent Manager",
  "notifBadgeAccepted": "Badge Aceite",
  "notifApplicationRejected": "Candidatura Rejeitada",
  "notifApproved": "Aprovado",
  "notifRejected": "Rejeitado",
  "notifExpiration": "Expiração",
  "notifGeneric": "Notificação",
  "completed": "Concluído",
  "primary": "Principal"
}
''';
