import 'dart:convert';

final Map<String, String> sourceStringsEn = Map.unmodifiable(
  (json.decode(_sourceJsonEn) as Map<String, dynamic>)
      .map((k, v) => MapEntry(k, v.toString())),
);

const _sourceJsonEn = r'''
{
  "appTitle": "Softinsa Badge Platform",
  "evolutionHello": "Hello",
  "timelineTitle": "Timeline",
  "timelineEmpty": "No activity to show yet.",
  "timelineRegistration": "Account created",
  "timelineBadgeEarned": "Badge earned",
  "timelinePointsGained": "Earned {points} points",
  "savedBadgesTitle": "Saved Badges",
  "savedBadgesEmptyTitle": "No saved badges",
  "savedBadgesEmptySubtitle": "Save badges to easily find them later.",
  "notificationsScreenTitle": "Your notifications",
  "notificationsMarkAllShort": "Mark all",
  "notificationsFilterAll": "All",
  "notificationsTabRecent": "Recent",
  "notificationsTabAll": "All",
  "notificationsEmpty": "No notifications to display.",
  "termsScreenTitle": "Terms and Conditions",
  "termsSection1Title": "1. Acceptance of Terms",
  "termsSection1Body": "By accessing and using the Softinsa Badge Platform, the user agrees to comply with these Terms and Conditions. If you do not agree with any of the conditions described herein, you should not use the platform.",
  "termsSection2Title": "2. Service Description",
  "termsSection2Body": "The Softinsa Badge Platform is a digital credentials system that allows Softinsa consultants to track, validate and share their technological skills and certifications through Learning Paths, Service Lines and Areas.",
  "termsSection3Title": "3. Registration and Account",
  "termsSection3Body": "The user is responsible for maintaining the confidentiality of their access credentials. Any activity carried out on the account is the responsibility of the account holder. Sharing credentials with third parties is prohibited.",
  "termsSection4Title": "4. Platform Usage",
  "termsSection4Body": "The platform is intended exclusively for professional use within the scope of Softinsa activities. The user agrees not to use the platform for unlawful purposes, not to upload offensive or inappropriate content, and to respect the intellectual property of all materials made available.",
  "termsSection5Title": "5. Badges and Certifications",
  "termsSection5Body": "The badges obtained represent skills validated by Softinsa. Accumulated points are permanently preserved on the consultant's profile, even if the badge reaches its expiration date. Each earned credential generates a unique public URL for external verification.",
  "termsSection6Title": "6. Data Protection (GDPR)",
  "termsSection6Body": "Softinsa is committed to protecting users' personal data in compliance with the General Data Protection Regulation (GDPR). The data collected is used exclusively for the operation of the platform and will not be shared with third parties without the user's prior consent, except when required by law.",
  "termsSection7Title": "7. Intellectual Property",
  "termsSection7Body": "All content, logos, design and functionalities of the platform are the property of Softinsa. The reproduction, distribution or modification of any content without prior authorisation is strictly prohibited.",
  "termsSection8Title": "8. Changes to Terms",
  "termsSection8Body": "Softinsa reserves the right to modify these Terms and Conditions at any time. Users will be notified of significant changes through the platform.",
  "termsSection9Title": "9. Contact",
  "termsSection9Body": "For questions related to these terms, please contact the Softinsa support team through the internal channels available on the platform.",
  "termsLastUpdate": "Last updated: May 2026",
  "loading": "Loading...",
  "back": "Back",
  "tryAgain": "Try again",
  "submit": "Submit",
  "area": "Area",
  "level": "Level",
  "date": "Date",
  "points": "Points",
  "description": "Description",
  "skills": "Skills",
  "requirements": "Requirements",
  "notes": "Notes",
  "openLink": "Open link",
  "removeFile": "Remove file",
  "screenNotAvailable": "Screen not yet available.",
  "welcomeBack": "Welcome back",
  "loginSubtitle": "Enter your credentials to continue.",
  "emailOrUsername": "Email or username",
  "emailOrUsernameHint": "Enter your email or username",
  "emailOrUsernameRequired": "Email or username is required.",
  "usernameMinChars": "Username must be at least 3 characters.",
  "password": "Password",
  "enterPasswordHint": "Enter your password",
  "saveLoginData": "Remember me",
  "forgotPassword": "Forgot your password?",
  "login": "Sign in",
  "noAccount": "Don't have an account?",
  "register": "Register",
  "loginSuccess": "Welcome back, {user}!",
  "loginErrorInvalidCredentials": "Login error. Please check your credentials.",
  "loginErrorServer": "Error connecting to the server.",
  "createAccount": "Create account",
  "registerTitle": "Create your account",
  "registerSubtitle": "Fill in the details to create your account.",
  "name": "Name",
  "nameHint": "John Smith",
  "username": "Username",
  "usernameHint": "johnsmith",
  "email": "Email",
  "emailHint": "your.email@softinsa.com",
  "createPasswordHint": "Create a secure password",
  "confirmPassword": "Confirm password",
  "confirmPasswordHint": "Confirm your password",
  "optionalFields": "Optional fields",
  "phone": "Phone",
  "phoneHint": "912 345 678",
  "invalidPhone": "Invalid phone number.",
  "birthdate": "Date of birth",
  "birthdateHint": "DD/MM/YYYY",
  "profileImage": "Profile image",
  "noFileSelected": "No file selected",
  "imageSelected": "Image selected",
  "imageUploadFailed": "Failed to upload image to the server.",
  "pickFromPhone": "Choose from phone",
  "location": "Location",
  "selectLocation": "Select location",
  "preferredLanguageOptional": "Preferred language (optional)",
  "selectLanguage": "Select language",
  "aboutMe": "About me",
  "aboutMeHint": "Tell us a bit about your career, goals and interests.",
  "acceptTermsPrefix": "I accept the ",
  "termsAndConditions": "terms and conditions",
  "andThe": " and the ",
  "privacyPolicy": "privacy policy",
  "mustAcceptTerms": "You must accept the terms and conditions.",
  "finishRegister": "Complete registration",
  "alreadyHaveAccount": "Already have an account?",
  "doLogin": "Sign in",
  "passwordsDoNotMatch": "Passwords do not match.",
  "selectAreasDescription": "Choose up to 5 areas of expertise and mark your main area.",
  "maxFiveAreas": "You can select a maximum of 5 areas.",
  "areasLoadFailed": "Failed to load areas: {error}",
  "noAreasAvailable": "No areas available.",
  "areasEditHint": "The first selected area is the main one. Minimum 1, maximum 5.",
  "areasMinRequired": "You must select at least 1 area.",
  "areas": "Areas",
  "confirmRegister": "Confirm registration",
  "registerSummary": "Registration summary",
  "personalData": "Personal data",
  "notFilled": "Not filled in",
  "notFilledF": "Not filled in",
  "selectedAreas": "Selected areas",
  "mainArea": "Main area",
  "notDefined": "Not defined",
  "noneSelectedArea": "No area selected.",
  "chooseAreasTitle": "Choose areas",
  "chooseAreasMenuLabel": "Choose areas",
  "chooseAreasMainSectionTitle": "Selected areas",
  "chooseAreasMainHint": "Tap a selected area to set it as main.",
  "chooseAreasNoneSelected": "You have not selected any area yet.",
  "chooseAreasAvailableTitle": "Available areas",
  "chooseAreasChooseHint": "Choose between 1 and 5 areas for your profile.",
  "chooseAreasConfirm": "Confirm my areas.",
  "chooseAreasSavedSuccess": "Areas updated successfully.",
  "chooseAreasSaveError": "Could not update areas.",
  "registerUser": "Register user",
  "userRegisteredSuccess": "User {username} registered successfully!",
  "registerErrorInvalidData": "Error registering user. Please check the data.",
  "unexpectedError": "An unexpected error occurred: {error}",
  "recoverPassword": "Recover password",
  "recoverSubtitle": "Enter your email to receive recovery instructions.",
  "sendInstructions": "Send instructions",
  "emailSentTo": "Instructions sent to {email}",
  "emailSent": "Email sent!",
  "checkMailbox": "Check your inbox and follow the instructions.",
  "backToLogin": "Back to login",
  "didNotReceiveEmail": "Didn't receive the email?",
  "checkSpam": "Also check your spam folder.",
  "dashboardGreeting": "Good afternoon, {name}!",
  "recentSubmissions": "Recent submissions",
  "forYou": "For you",
  "keepGoing": "Keep it up!",
  "motivationNotRanked": "Take the first step!",
  "motivationTop10": "Outstanding!",
  "motivationTop25": "Great job!",
  "motivationTop50": "Keep it up!",
  "motivationTop75": "You're on your way!",
  "motivationBottom": "You can do it!",
  "dashboardTopPercentPrefix": "You are in the top ",
  "dashboardTopPercentMiddle": " of those who earned the most ",
  "dashboardTopPercentHighlight": "badges",
  "dashboardTopPercentSuffix": " last week.",
  "dashboardAreaLowCode": "LowCode",
  "dashboardAreaDevSecOps": "DevSecOps",
  "dashboardAreaUxUi": "UX/UI Design",
  "dashboardAreaAutomation": "Automation",
  "submissionStatusInReview": "In review",
  "submissionStatusRejected": "Rejected",
  "submissionStatusApproved": "Approved",
  "statistics": "Statistics",
  "completedBadges": "Completed badges",
  "areasWithCertifications": "Areas with\ncertifications",
  "totalBadges": "Badges",
  "certificationsByArea": "Certifications by area",
  "noBadgesYet": "No badges yet",
  "monthApril": "April",
  "monthMay": "May",
  "monthJune": "June",
  "monthJuly": "July",
  "monthAugust": "August",
  "navExplore": "Explore",
  "navBadges": "Badges",
  "navHome": "Home",
  "navProgress": "Progress",
  "navProfile": "Profile",
  "exploreCompetenciesTitle": "Explore new skills",
  "searchBadgeHint": "Search for your badge",
  "noBadgesAvailable": "No badges available.",
  "filtersAndSorting": "Filters and sorting",
  "sortBy": "Sort by",
  "sortMostRecent": "Most recent",
  "sortOldest": "Oldest",
  "sortMostPoints": "Most points",
  "areaFrontend": "Frontend",
  "areaBackend": "Backend",
  "areaFullstack": "Fullstack",
  "areaAi": "AI",
  "levelBeginner": "Beginner",
  "levelIntermediate": "Intermediate",
  "levelExpert": "Expert",
  "badgeType": "Badge type",
  "badgeTypeNormal": "Normal",
  "badgeTypeSpecial": "Special",
  "last7Days": "Last 7 days",
  "last30Days": "Last 30 days",
  "thisYear": "This year",
  "overviewTab": "Overview",
  "detailsTab": "Details",
  "submitApplication": "Submit application",
  "applicationTitle": "Application",
  "applicationSectionBadge": "Selected badge",
  "applicationSectionEvidence": "Submit evidence",
  "applicationSectionTerms": "Terms and conditions",
  "applicationSectionSubmission": "Submission",
  "applicationAttachFile": "Attach file",
  "applicationAttachedFileSubtitle": "Associated with all badge requirements",
  "noRequirementsLinked": "No linked requirement.",
  "applicationSubmissionDisclaimer": "By submitting this application, you confirm that the evidence is truthful and authorise validation by the responsible team.",
  "applicationStatusTitle": "Application status",
  "applicationStatusForBadge": "Application for badge \"{badge}\"",
  "latestUpdates": "Latest updates",
  "applicationInReviewBySll": "In review by Service Line Leader",
  "applicationStatusTimestamp": "01/11/2025 at 17:23",
  "talentManagerLabel": "Talent Manager",
  "applicationStatusPlaceholderNote": "We are validating the submitted evidence and confirming alignment with badge requirements.",
  "attachedFiles": "Attached files",
  "similarBadges": "Similar badges",
  "badgeInfo": "Badge information",
  "stepSubmitted": "Submitted",
  "stepTm": "TM",
  "stepServiceLineLeader": "Service Line Leader",
  "validationNameRequired": "Name is required.",
  "validationNameMinChars": "Name must be at least 2 characters.",
  "validationUsernameRequired": "Username is required.",
  "validationUsernameMinChars": "Username must be at least 3 characters.",
  "validationUsernameInvalidChars": "Username can only contain letters, numbers, dots and underscores.",
  "validationEmailRequired": "Email is required.",
  "validationEmailInvalidFormat": "Invalid email format.",
  "validationPasswordRequired": "Password is required.",
  "validationPasswordMinChars": "Password must be at least 8 characters.",
  "validationPasswordConfirmRequired": "Please confirm your password.",
  "validationPasswordConfirmMismatch": "Passwords do not match.",
  "validationBirthdateFormat": "Date must be in dd/mm/yyyy format.",
  "validationBiographyMaxChars": "Biography must be at most 1000 characters.",
  "monthJanuary": "January",
  "monthFebruary": "February",
  "monthMarch": "March",
  "monthSeptember": "September",
  "monthOctober": "October",
  "monthNovember": "November",
  "monthDecember": "December",
  "monthShortJan": "Jan",
  "monthShortFeb": "Feb",
  "monthShortMar": "Mar",
  "monthShortApr": "Apr",
  "monthShortMay": "May",
  "monthShortJun": "Jun",
  "monthShortJul": "Jul",
  "monthShortAug": "Aug",
  "monthShortSep": "Sep",
  "monthShortOct": "Oct",
  "monthShortNov": "Nov",
  "monthShortDec": "Dec",
  "editProfile": "Edit Profile",
  "fullName": "Full name",
  "biography": "Biography",
  "biographyHint": "Write something about yourself...",
  "selectLocationLabel": "Select location",
  "saveChanges": "Save Changes",
  "profileUpdatedSuccess": "Profile updated successfully.",
  "profileUpdateError": "Error updating profile.",
  "pointsTitle": "Points",
  "pointsLabel": "points",
  "history": "History",
  "noPointsHistory": "No points history.",
  "topPercentMessage": "You are in the top {percent}% of our consultants!",
  "seeMore": "See more",
  "seeLess": "See less",
  "weeklyPoints": "Points this week",
  "monthlyPoints": "Points per month",
  "noDataAvailable": "No data available.",
  "badgesEarned": "badges earned",
  "selectLanguageTitle": "Select language",
  "usernameUnavailable": "Username unavailable.",
  "usernameMinCharsEdit": "Minimum of 3 characters.",
  "nameRequired": "Name is required.",
  "languageLabel": "Language",
  "goodMorning": "Good morning",
  "goodAfternoon": "Good afternoon",
  "goodEvening": "Good evening",
  "pwReqMinChars": "Minimum of 8 characters",
  "pwReqUppercase": "At least 1 uppercase letter",
  "pwReqLowercase": "At least 1 lowercase letter",
  "pwReqNumber": "At least 1 number",
  "pwReqSpecialChar": "At least 1 special character (!@#$%^&*)",
  "loginErrorUserNotFound": "User or email not found.",
  "loginErrorWrongPassword": "Incorrect password.",
  "loginErrorAccountDeactivated": "Your account has been deactivated. Please contact the administrator.",
  "loginErrorAccountLocked": "Account locked due to excessive attempts. Please try again in 15 minutes.",
  "rejectedByTM": "Rejected by Talent Manager",
  "rejectedBySL": "Rejected by Service Line Leader",
  "fileTooLarge": "The file is too large. The maximum allowed size is {size} MB.",
  "fileUploadError": "Could not upload the file. Please try again.",
  "downloadingFile": "Downloading file...",
  "fileDownloaded": "File downloaded successfully.",
  "fileDownloadError": "Could not download the file.",
  "openingLink": "Opening link...",
  "certifiedCompetences": "Certified Skills",
  "competenceCount_one": "skill",
  "competenceCount_other": "skills",
  "celebrationFirstBadgeTitle": "First Badge!",
  "celebrationFirstBadgeDesc": "Congratulations! You earned your first badge. Your certification journey has begun!",
  "celebration3BadgesTitle": "Gaining Momentum!",
  "celebration3BadgesDesc": "3 badges in the bag! You're warming up and your effort is showing. Don't stop now!",
  "celebration5BadgesTitle": "Rising Star!",
  "celebration5BadgesDesc": "Incredible! 5 badges earned. You're building an impressive skills portfolio!",
  "celebration10BadgesTitle": "Badge Collector!",
  "celebration10BadgesDesc": "10 badges earned! Your dedication is paying off and the team recognizes your value.",
  "celebration20BadgesTitle": "Certified Expert!",
  "celebration20BadgesDesc": "20 badges! You're now a reference in the team. Your knowledge makes a difference every day.",
  "celebration35BadgesTitle": "Elite Level!",
  "celebration35BadgesDesc": "35 extraordinary badges! Few reach this level. Your journey is truly inspiring.",
  "celebration50BadgesTitle": "Badge Master!",
  "celebration50BadgesDesc": "50 badges! A legendary achievement. You are a true pillar of excellence at Softinsa!",
  "modelDownloadFailed": "Could not download the translation model. Please check your internet connection.",
  "tabEarnedBadges": "Earned Badges",
  "tabApplications": "Applications",
  "myBadgesSearchHint": "Search badges",
  "applicationsSearchHint": "Search applications, badges",
  "noBadgesFound": "No badges found.",
  "noEarnedBadgesYet": "You have not earned any badges yet.",
  "noApplicationsFound": "No applications found.",
  "applicationsLoadFailedLocal": "Could not load applications. Showing local data.",
  "filterAll": "All",
  "filterApproved": "Approved",
  "filterInReview": "In review",
  "filterRejected": "Rejected",
  "stateApproved": "Approved",
  "stateRejected": "Rejected",
  "stateInValidation": "In validation",
  "proofDocument": "Proof document",
  "share": "Share",
  "special": "Special",
  "expiresOn": "Expires on",
  "badgeSharedSuccess": "Badge shared successfully!",
  "couldNotOpenLink": "Could not open the link.",
  "couldNotIdentifyApplication": "Could not identify the application associated with this badge.",
  "downloadingProof": "Downloading proof document...",
  "proofDownloadError": "Error downloading proof document.",
  "gdprConsentError": "Could not register GDPR consent. Please try again.",
  "approvedToday": "Approved today",
  "approvedOneDayAgo": "Approved 1 day ago",
  "approvedDaysAgo": "Approved {days} days ago",
  "shortTimeAgo": "just now",
  "minutesAgo": "{minutes} minutes ago",
  "hoursAgo": "{hours} hours ago",
  "daysAgo": "{days} days ago",
  "consultantFallback": "Consultant",
  "userFallback": "User",
  "primaryAreaNotDefined": "Main area not defined",
  "technicalJourney": "Technical Journey",
  "badgesMetric": "Badges",
  "skillsMetric": "Skills",
  "badgeGalleryTitle": "Badge Gallery",
  "badgeGallerySubtitle": "View and manage your achievement badges",
  "galleryUpdateError": "Couldn't update the gallery. Please try again.",
  "viewGallery": "View gallery",
  "settings": "Settings",
  "myCharacteristics": "My characteristics",
  "notificationPreferences": "Notification preferences",
  "notificationChannelPush": "Push notifications",
  "notificationChannelEmail": "Email",
  "notificationPreferencesError": "Couldn't update the preferences. Please try again.",
  "notificationPreferencesEmpty": "There are no notification preferences available.",
  "changePasswordAction": "Change password",
  "emailSignature": "Email signature",
  "languageChangeError": "Error changing language.",
  "helpAndPolicies": "Help and policies",
  "privacyPolicies": "Privacy policies",
  "termsAndConditionsTitle": "Terms and conditions",
  "help": "Help",
  "logout": "Sign out",
  "appVersion": "Version {version}",
  "activeBadgesCount": "{count} active",
  "noEvolutionData": "No progress data.",
  "badgesByYear": "Badges by year",
  "evolutionGreeting": "Hello, {name}!",
  "badgesObtained": "Badges obtained",
  "activeAchievements": "Active achievements",
  "levelsCompleted": "Levels completed",
  "totalPoints": "Total points",
  "periodWeekly": "Weekly",
  "periodMonthly": "Monthly",
  "periodYearly": "Yearly",
  "recentActivity": "Recent activity",
  "timeAgoValue": "{time} ago",
  "applications": "Applications",
  "approvalPercentage": "Approval percentage",
  "submittedApplications": "Submitted applications",
  "learningPathProgress": "Learning Path progress",
  "badgesPerArea": "Badges per area",

  "helpQuestionTitle": "How can I help you?",
  "helpQuestionSubtitle": "Explore the application features and learn how to get the most out of the platform.",
  "helpFeatures": "Features",
  "helpDashboardTitle": "Dashboard",
  "helpDashboardDesc": "The Dashboard is your home page. Here you can see a summary of your activities, recent announcements, your progress and the overall platform ranking.",
  "helpExploreTitle": "Explore Skills",
  "helpExploreDesc": "In this section you can browse all badges available on the platform. Use the filters to search by area, level, points or date. Tap a badge to see its details and start an application.",
  "helpMyBadgesTitle": "My Badges",
  "helpMyBadgesDesc": "View the badges you have already earned in the \"Earned Badges\" tab and track the status of your applications in the \"Applications\" tab. You can share or download earned badges.",
  "helpEvolutionTitle": "Progress",
  "helpEvolutionDesc": "The Progress section shows your development over time: accumulated points, badges earned and your ranking position. Track the growth of your technical journey.",
  "helpProfileTitle": "Profile",
  "helpProfileDesc": "In your profile you can view and edit your personal information, change the application language, check your characteristics, manage the email signature and access account settings.",
  "helpApplicationsTitle": "Applications",
  "helpApplicationsDesc": "To obtain a badge, start an application on the badge details page. Attach the necessary evidence (files, certificates) and submit. The application will be evaluated by the Talent Manager and then by the Service Line Leader.",
  "helpNotificationsTitle": "Notifications",
  "helpNotificationsDesc": "Receive alerts about the status of your applications, expiring badges, and other relevant updates. You can mark notifications as read individually or all at once.",
  "helpShareTitle": "Badge Sharing",
  "helpShareDesc": "After obtaining a badge, you can share it publicly. On the first share, GDPR consent will be requested. Shared badges are accessible through a public verification link.",

  "iAmIntro": "I {name} am",
  "noCharacteristicsDefined": "No characteristics defined yet.",

  "selectBadgesToShow": "Select Badges to display",
  "recentFilter": "Recent",
  "previewLabel": "Preview",
  "previewBefore": "Before",
  "previewAfter": "After",
  "noBadgeSelected": "No badge selected",
  "confirmEmailSignatureAction": "Confirm Email signature",
  "saveAndSendSignature": "Save and send your signature",
  "selectAtLeastOneBadge": "Select at least one badge.",
  "emailSignatureSaved": "Email signature saved successfully.",
  "emailSignatureSaveError": "Error saving the email signature.",

  "welcomeFirstLogin": "Welcome!",
  "firstLoginPasswordPrompt": "For security, please set a new password for your account.",
  "currentPassword": "Current password",
  "newPassword": "New password",
  "enterCurrentPassword": "Enter your current password.",
  "changePasswordButton": "Change Password",
  "changePasswordSuccess": "Password changed successfully.",
  "changePasswordErrorGeneric": "Error changing password.",
  "errorCurrentPasswordWrong": "The current password is incorrect. Please check and try again.",
  "errorPasswordFormatInvalid": "The new password does not meet the security requirements.",
  "errorPasswordSameAsCurrent": "The new password cannot be the same as the current password.",

  "applicationStartError": "Error starting application.",
  "applicationExistsInState": "An application in \"{state}\" status already exists for this badge.",
  "applicationGuidError": "Error: Application GUID not received.",
  "applicationSubmitError": "Error submitting application.",
  "submitting": "Submitting...",

  "applicationSubmitted": "Application submitted",
  "applicationReceivedSuccess": "Your application was received successfully!",
  "badgeTypeLabel": "Badge Type",
  "submittedAtLabel": "Submitted on",
  "confirmationSentTo": "Confirmation sent to",
  "nextSteps": "Next steps",
  "nextStepEvaluation": "Application will be evaluated",
  "nextStepResult": "You will receive a result in about 5 days",
  "viewApplicationStatus": "View application status",
  "backToMenu": "Back to Menu",

  "confirmYourApplication": "Confirm your application",
  "applicationSubmittedSuccess": "Your application was submitted successfully!",
  "sendConfirmationInstruction": "To finalise, send the confirmation email of your application for the badge:",
  "sending": "Sending...",
  "sendConfirmationEmail": "Send confirmation email",
  "emailResendUnavailable": "Email resend is currently unavailable. The original email was sent with the submission.",
  "emailSendError": "Error sending confirmation email.",
  "emailResendFailed": "Could not resend the email. Please try again later.",
  "confirmationEmailSentTo": "We sent a confirmation email to:",
  "applicationWillBeEvaluated": "Your application will be evaluated by the Talent Manager and the Service Line Leader. You will receive a notification with the result.",
  "resendEmailCooldown": "Resend email ({seconds} s)",
  "resendEmail": "Resend email",
  "emailNotReceived": "Didn't receive the email? Check your spam folder.",

  "applicationApprovedSuccess": "Application approved successfully!",
  "inReviewBySLL": "In review by Service Line Leader",
  "inReviewByTM": "In review by Talent Manager",
  "applicationOpen": "Application open",
  "progress": "Progress",
  "stepSubmittedLabel": "Submitted",
  "stepApprovedLabel": "Approved",
  "details": "Details",
  "openedAt": "Opened on",
  "observation": "Observation",
  "badgeInformation": "Badge information",
  "createdAt": "Created on",
  "validityDays": "Validity: {days} days",
  "applicationDetails": "Application details",
  "applicationSubmittedDialog": "Application submitted!",
  "applicationSubmittedDialogDesc": "Your application was submitted successfully and will be evaluated shortly.",
  "viewApplication": "View application",
  "viewBadges": "View badges",

  "stateApprovedF": "Approved",
  "stateRejectedF": "Rejected",
  "stateInValidationF": "In validation",
  "stateSubmittedF": "Submitted",
  "stateInAnalysis": "In review",
  "badgeSaved": "Badge saved!",
  "badgeUnsaved": "Badge removed from saved.",
  "linkCopied": "Link copied to clipboard!",
  "estimatedDuration": "Estimated duration",
  "duration": "Duration",
  "validity": "Validity",
  "markAsRead": "Mark as read",
  "deleteNotification": "Delete notification",
  "timeNow": "Now",
  "notifTypeHome": "Home",
  "notifTypeBadges": "Badges",
  "notifTypeApplications": "Applications",
  "notifTypeAchievements": "Achievements",
  "notifTypePoints": "Points",
  "notifTypeObjectives": "Goals",
  "notifTypeEvolution": "Progress",
  "notifTypeAnnouncements": "Announcements",
  "notifTypeSystem": "System",
  "notifApplicationSubmitted": "Application Submitted",
  "notifApprovedByTm": "Approved by Talent Manager",
  "notifBadgeAccepted": "Badge Accepted",
  "notifApplicationRejected": "Application Rejected",
  "notifApproved": "Approved",
  "notifRejected": "Rejected",
  "notifExpiration": "Expiration",
  "notifGeneric": "Notification",
  "completed": "Completed",
  "primary": "Primary",
  "addAsGoal": "Add as goal",
  "goalAdded": "Badge added as goal!",
  "goalAddError": "Error adding goal.",
  "copyHtmlCode": "Copy code",
  "htmlCopied": "Code copied!",
  "emailSignatureInstructions": "Instructions",
  "gmailInstructions": "Gmail: Settings → See all settings → General → Signature → Paste the code",
  "outlookInstructions": "Outlook: File → Options → Mail → Signatures → New → Paste the code",
  "serviceLine": "Service Line",
  "learningPath": "Learning Path",
  "badgeType": "Type",
  "removeGoal": "Remove goal",
  "removing": "Removing...",
  "goalRemoved": "Goal removed.",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "confirmConclusion": "Complete goal",
  "concluding": "Completing...",
  "goalConcluded": "Goal completed!",
  "goalNotOwned": "You haven't earned this badge yet.",
  "goalCompleteError": "Could not complete the goal.",
  "goalDeadlineTitle": "Set goal deadline",
  "goalDeadlineSubtitle": "Choose in how many months you want to complete this goal.",
  "goalDeadlinePreview": "Deadline: {date}",
  "durationMonth": "month",
  "durationMonths": "months",
  "NOTIF_APP_SUBMITTED_TITLE": "Application submitted",
  "NOTIF_APP_SUBMITTED_BODY": "Your application for the badge \"{{badgeTitle}}\" was submitted successfully.",
  "NOTIF_APP_NEW_APPLICATION_TITLE": "New application received",
  "NOTIF_APP_NEW_APPLICATION_BODY": "A new application for the badge \"{{badgeTitle}}\" is awaiting review.",
  "NOTIF_APP_BADGE_AWARDED_TITLE": "Congratulations, you earned a badge!",
  "NOTIF_APP_BADGE_AWARDED_BODY": "The badge \"{{badgeTitle}}\" has been awarded to you. Keep it up, every badge brings you closer to excellence!",
  "NOTIF_APP_SPECIAL_BADGE_AWARDED_TITLE": "Special badge unlocked!",
  "NOTIF_APP_SPECIAL_BADGE_AWARDED_BODY": "Amazing! You earned the special badge \"{{badgeTitle}}\". This is a remarkable achievement — keep pushing forward!",
  "NOTIF_APP_REJECTED_TITLE": "Application rejected",
  "NOTIF_APP_REJECTED_BODY": "Your application for the badge \"{{badgeTitle}}\" has been rejected.",
  "NOTIF_APP_IN_VALIDATION_TITLE": "Application in validation",
  "NOTIF_APP_IN_VALIDATION_BODY": "Your application for the badge \"{{badgeTitle}}\" is now being validated.",
  "NOTIF_APP_PENDING_SLL_REVIEW_TITLE": "Application awaiting review",
  "NOTIF_APP_PENDING_SLL_REVIEW_BODY": "An application for the badge \"{{badgeTitle}}\" is awaiting your review.",
  "NOTIF_BADGE_EXPIRING_SOON_TITLE": "Badge expiring soon",
  "NOTIF_BADGE_EXPIRING_SOON_BODY": "Your badge \"{{badgeTitle}}\" expires in {{daysRemaining}} days.",
  "NOTIF_BADGE_EXPIRED_TITLE": "Badge expired",
  "NOTIF_BADGE_EXPIRED_BODY": "Your badge \"{{badgeTitle}}\" has expired.",
  "NOTIF_SLA_BREACH_TITLE": "SLA breach",
  "NOTIF_SLA_BREACH_BODY": "The SLA \"{{slaName}}\" was exceeded by {{hoursExceeded}}h for the badge \"{{badgeTitle}}\".",
  "NOTIF_CUSTOM_SLA_BREACH_TITLE": "Custom SLA breach",
  "NOTIF_CUSTOM_SLA_BREACH_BODY": "The SLA \"{{slaName}}\" has reached its deadline.",
  "NOTIF_GOAL_REMINDER_TITLE": "Goal reminder",
  "NOTIF_GOAL_REMINDER_BODY": "Don't forget about your goal \"{{goalTitle}}\".",
  "NOTIF_GOAL_DEADLINE_APPROACHING_TITLE": "Goal deadline approaching",
  "NOTIF_GOAL_DEADLINE_APPROACHING_BODY": "Your goal \"{{goalTitle}}\" is due in {{daysRemaining}} days.",

  "policyTypePrivacy": "Privacy Policy",
  "policyTypeTerms": "Terms and Conditions",
  "policyTypeCookies": "Cookie Policy",

  "includeOptions": "Include",
  "includePhoto": "Include photo",
  "includeName": "Include name",
  "viewSignature": "View signature",
  "viewEmailTemplate": "View email template",
  "copySignature": "Copy signature",
  "copyEmailTemplate": "Copy email template",
  "signatureNoBadgesNote": "Only consultants can include badges in the email signature.",
  "roleConsultant": "Consultant",
  "roleTalentManager": "Talent Manager",
  "roleServiceLineLeader": "Service Line Leader",
  "roleAdministrator": "Administrator",

  "emailConfirmationTitle": "Email sent!",
  "emailConfirmationSentTo": "We sent a confirmation email to:",
  "emailConfirmationInstructions": "Click the link sent to your email to activate your account. After confirmation, you will be able to log in to the application.",
  "goToLogin": "Go to Login",
  "resendConfirmationBtn": "Resend email",
  "resendConfirmationCooldown": "Resend email ({seconds} s)",
  "resendConfirmationError": "Error resending confirmation email.",
  "resendConfirmationErrorRetry": "Error resending email. Please try again.",
  "checkSpamHint": "Didn't receive the email? Check your spam folder or try resending.",
  "rateLimitedRetry": "Please wait {seconds} seconds before trying again.",

  "resetPasswordTitle": "Reset password",
  "resetPasswordSubtitle": "Enter your new password.",
  "validatingLink": "Validating link...",
  "invalidOrExpiredTitle": "Invalid or expired link",
  "invalidOrExpiredDesc": "The password reset link is invalid or has expired. Please request a new link.",
  "tokenExpired": "The link has expired. Please request a new reset link.",
  "requestNewLink": "Request new link",
  "confirmNewPassword": "Confirm new password",
  "resetPasswordBtn": "Reset password",
  "resetPasswordSuccess": "Password reset!",
  "resetPasswordSuccessDesc": "Your password has been reset successfully. You can now log in with your new password.",

  "confirmingEmail": "Confirming your email...",
  "emailConfirmedTitle": "Email confirmed!",
  "emailConfirmedDesc": "Your email has been confirmed successfully. You can now log in to the application.",
  "confirmationFailed": "Confirmation failed",
  "confirmationFailedDesc": "Could not confirm your email. The link may be invalid or have expired.",

  "loginErrorConsultantOnly": "Only Consultant accounts can access the mobile application.",
  "loginErrorEmailNotConfirmed": "Your email has not been confirmed yet. Please check your inbox.",

  "storeTitle": "Rewards Store",
  "storeSubtitle": "Spend your points on courses and perks.",
  "storePoints": "points",
  "storeRedeem": "Redeem",
  "storeNotEnough": "Not enough points",
  "storeEmpty": "No rewards available yet.",
  "storeMyRedemptions": "My redemptions",
  "storeAccess": "Access",
  "storeConfirmTitle": "Confirm redemption",
  "storeConfirmText": "Redeem \"{name}\" for {cost} points?",
  "storeSuccessTitle": "Reward redeemed!",
  "storeSuccessText": "You successfully redeemed \"{name}\".",
  "storeEmailNote": "We've emailed you the access details.",
  "storeMyTitle": "My title",
  "storeMyTitleHint": "Choose the title shown publicly on your profile (from the ones you unlocked).",
  "storeNoTitle": "None",
  "storeRewardsStore": "Rewards Store",
  "storeSpendPoints": "Spend points",

  "rewardsTitle": "Rewards",
  "rewardsDescription": "By earning this badge, unlock an exclusive specialist title and an official certificate validating your progression at Softinsa.",
  "rewardCertificatePdf": "PDF Certificate",
  "rewardCertificateDesc": "Official downloadable certificate",
  "rewardSpecialTitle": "Special title"
}
''';
