import 'dart:convert';

final Map<String, String> sourceStringsEs = Map.unmodifiable(
  (json.decode(_sourceJsonEs) as Map<String, dynamic>)
      .map((k, v) => MapEntry(k, v.toString())),
);

const _sourceJsonEs = r'''
{
  "appTitle": "Plataforma de Badges Softinsa",
  "evolutionHello": "Hola",
  "savedBadgesTitle": "Badges Guardados",
  "savedBadgesEmptyTitle": "Ningún badge guardado",
  "savedBadgesEmptySubtitle": "Guarda badges para encontrarlos fácilmente más tarde.",
  "notificationsScreenTitle": "Sus notificaciones",
  "notificationsMarkAllShort": "Marcar todas",
  "notificationsFilterAll": "Todas",
  "notificationsTabRecent": "Recientes",
  "notificationsTabAll": "Todas",
  "notificationsEmpty": "Sin notificaciones para mostrar.",
  "termsScreenTitle": "Términos y Condiciones",
  "termsSection1Title": "1. Aceptación de los Términos",
  "termsSection1Body": "Al acceder y utilizar la plataforma Softinsa Badge Platform, el usuario acepta cumplir los presentes Términos y Condiciones. Si no está de acuerdo con alguna de las condiciones aquí descritas, no deberá utilizar la plataforma.",
  "termsSection2Title": "2. Descripción del Servicio",
  "termsSection2Body": "La Softinsa Badge Platform es un sistema de credenciales digitales que permite a los consultores de Softinsa seguir, validar y compartir sus competencias y certificaciones tecnológicas a través de Learning Paths, Service Lines y Áreas.",
  "termsSection3Title": "3. Registro y Cuenta",
  "termsSection3Body": "El usuario es responsable de mantener la confidencialidad de sus credenciales de acceso. Cualquier actividad realizada en la cuenta es responsabilidad del titular. Está prohibido compartir credenciales con terceros.",
  "termsSection4Title": "4. Uso de la Plataforma",
  "termsSection4Body": "La plataforma está destinada exclusivamente al uso profesional en el ámbito de las actividades de Softinsa. El usuario se compromete a no utilizar la plataforma con fines ilícitos, a no subir contenidos ofensivos o inadecuados y a respetar la propiedad intelectual de todos los materiales disponibles.",
  "termsSection5Title": "5. Badges y Certificaciones",
  "termsSection5Body": "Los badges obtenidos representan competencias validadas por Softinsa. Los puntos acumulados se conservan permanentemente en el perfil del consultor, incluso si el badge alcanza su fecha de expiración. Cada credencial obtenida genera una URL pública única para verificación externa.",
  "termsSection6Title": "6. Protección de Datos (RGPD)",
  "termsSection6Body": "Softinsa se compromete a proteger los datos personales de los usuarios de conformidad con el Reglamento General de Protección de Datos (RGPD). Los datos recogidos se utilizan exclusivamente para el funcionamiento de la plataforma y no serán compartidos con terceros sin el consentimiento previo del usuario, salvo cuando lo exija la ley.",
  "termsSection7Title": "7. Propiedad Intelectual",
  "termsSection7Body": "Todos los contenidos, logotipos, diseño y funcionalidades de la plataforma son propiedad de Softinsa. La reproducción, distribución o modificación de cualquier contenido sin autorización previa está estrictamente prohibida.",
  "termsSection8Title": "8. Cambios en los Términos",
  "termsSection8Body": "Softinsa se reserva el derecho de modificar los presentes Términos y Condiciones en cualquier momento. Los usuarios serán notificados de cambios significativos a través de la plataforma.",
  "termsSection9Title": "9. Contacto",
  "termsSection9Body": "Para cuestiones relacionadas con estos términos, contacte con el equipo de soporte de Softinsa a través de los canales internos disponibles en la plataforma.",
  "termsLastUpdate": "Última actualización: mayo de 2026",
  "loading": "Cargando...",
  "back": "Volver",
  "tryAgain": "Intentar de nuevo",
  "submit": "Enviar",
  "area": "Área",
  "level": "Nivel",
  "date": "Fecha",
  "points": "Puntos",
  "description": "Descripción",
  "skills": "Competencias",
  "requirements": "Requisitos",
  "notes": "Observaciones",
  "openLink": "Abrir enlace",
  "removeFile": "Eliminar archivo",
  "screenNotAvailable": "Pantalla aún no disponible.",
  "welcomeBack": "Bienvenido de nuevo",
  "loginSubtitle": "Introduce tus credenciales para continuar.",
  "emailOrUsername": "Email o nombre de usuario",
  "emailOrUsernameHint": "Introduce tu email o nombre de usuario",
  "emailOrUsernameRequired": "El email o nombre de usuario es obligatorio.",
  "usernameMinChars": "El nombre de usuario debe tener al menos 3 caracteres.",
  "password": "Contraseña",
  "enterPasswordHint": "Introduce tu contraseña",
  "saveLoginData": "Guardar sesión",
  "forgotPassword": "¿Olvidaste tu contraseña?",
  "login": "Iniciar sesión",
  "noAccount": "¿No tienes cuenta?",
  "register": "Registrarse",
  "loginSuccess": "¡Bienvenido de nuevo, {user}!",
  "loginErrorInvalidCredentials": "Error en el inicio de sesión. Verifica tus credenciales.",
  "loginErrorServer": "Error al conectar con el servidor.",
  "createAccount": "Crear cuenta",
  "registerTitle": "Crea tu cuenta",
  "registerSubtitle": "Rellena los datos para crear tu cuenta.",
  "name": "Nombre",
  "nameHint": "Juan García",
  "username": "Nombre de usuario",
  "usernameHint": "juangarcia",
  "email": "Email",
  "emailHint": "tu.email@softinsa.com",
  "createPasswordHint": "Crea una contraseña segura",
  "confirmPassword": "Confirmar contraseña",
  "confirmPasswordHint": "Confirma tu contraseña",
  "optionalFields": "Campos opcionales",
  "phone": "Teléfono",
  "phoneHint": "912 345 678",
  "invalidPhone": "Número de teléfono no válido.",
  "birthdate": "Fecha de nacimiento",
  "birthdateHint": "DD/MM/AAAA",
  "profileImage": "Imagen de perfil",
  "noFileSelected": "Ningún archivo seleccionado",
  "imageSelected": "Imagen seleccionada",
  "imageUploadFailed": "Error al subir la imagen al servidor.",
  "pickFromPhone": "Elegir del teléfono",
  "location": "Ubicación",
  "selectLocation": "Seleccionar ubicación",
  "preferredLanguageOptional": "Idioma preferido (opcional)",
  "selectLanguage": "Seleccionar idioma",
  "aboutMe": "Sobre mí",
  "aboutMeHint": "Cuéntanos un poco sobre tu trayectoria, objetivos e intereses.",
  "acceptTermsPrefix": "Acepto los ",
  "termsAndConditions": "términos y condiciones",
  "andThe": " y la ",
  "privacyPolicy": "política de privacidad",
  "mustAcceptTerms": "Debes aceptar los términos y condiciones.",
  "finishRegister": "Completar registro",
  "alreadyHaveAccount": "¿Ya tienes cuenta?",
  "doLogin": "Iniciar sesión",
  "passwordsDoNotMatch": "Las contraseñas no coinciden.",
  "selectAreasDescription": "Elige hasta 5 áreas de especialización y marca tu área principal.",
  "maxFiveAreas": "Puedes seleccionar un máximo de 5 áreas.",
  "areasLoadFailed": "Error al cargar áreas: {error}",
  "noAreasAvailable": "Sin áreas disponibles.",
  "areasEditHint": "La primera área seleccionada es la principal. Mínimo 1, máximo 5.",
  "areasMinRequired": "Debes seleccionar al menos 1 área.",
  "areas": "Áreas",
  "confirmRegister": "Confirmar registro",
  "registerSummary": "Resumen del registro",
  "personalData": "Datos personales",
  "notFilled": "No rellenado",
  "notFilledF": "No rellenada",
  "selectedAreas": "Áreas seleccionadas",
  "mainArea": "Área principal",
  "notDefined": "No definido",
  "noneSelectedArea": "Ningún área seleccionada.",
  "chooseAreasTitle": "Elegir áreas",
  "chooseAreasMenuLabel": "Elegir áreas",
  "chooseAreasMainSectionTitle": "Áreas seleccionadas",
  "chooseAreasMainHint": "Toque un área seleccionada para definirla como principal.",
  "chooseAreasNoneSelected": "Aún no ha seleccionado ningún área.",
  "chooseAreasAvailableTitle": "Áreas disponibles",
  "chooseAreasChooseHint": "Elija entre 1 y 5 áreas para su perfil.",
  "chooseAreasConfirm": "Confirmar mis áreas.",
  "chooseAreasSavedSuccess": "Áreas actualizadas correctamente.",
  "chooseAreasSaveError": "No fue posible actualizar las áreas.",
  "registerUser": "Registrar usuario",
  "userRegisteredSuccess": "¡Usuario {username} registrado correctamente!",
  "registerErrorInvalidData": "Error al registrar usuario. Verifica los datos.",
  "unexpectedError": "Ocurrió un error inesperado: {error}",
  "recoverPassword": "Recuperar contraseña",
  "recoverSubtitle": "Introduce tu email para recibir instrucciones de recuperación.",
  "sendInstructions": "Enviar instrucciones",
  "emailSentTo": "Instrucciones enviadas a {email}",
  "emailSent": "¡Email enviado!",
  "checkMailbox": "Revisa tu bandeja de entrada y sigue las instrucciones.",
  "backToLogin": "Volver al inicio de sesión",
  "didNotReceiveEmail": "¿No recibiste el email?",
  "checkSpam": "Revisa también la carpeta de spam.",
  "dashboardGreeting": "¡Buenas tardes, {name}!",
  "recentSubmissions": "Envíos recientes",
  "forYou": "Para ti",
  "keepGoing": "¡Sigue así!",
  "motivationNotRanked": "¡Da el primer paso!",
  "motivationTop10": "¡Sobresaliente!",
  "motivationTop25": "¡Gran trabajo!",
  "motivationTop50": "¡Sigue así!",
  "motivationTop75": "¡Vas por buen camino!",
  "motivationBottom": "¡Tú puedes!",
  "dashboardTopPercentPrefix": "Estás en el top ",
  "dashboardTopPercentMiddle": " de los que más ",
  "dashboardTopPercentHighlight": "badges conquistaron",
  "dashboardTopPercentSuffix": " la semana pasada.",
  "dashboardAreaLowCode": "LowCode",
  "dashboardAreaDevSecOps": "DevSecOps",
  "dashboardAreaUxUi": "Diseño UX/UI",
  "dashboardAreaAutomation": "Automatización",
  "submissionStatusInReview": "En revisión",
  "submissionStatusRejected": "Rechazado",
  "submissionStatusApproved": "Aprobado",
  "statistics": "Estadísticas",
  "completedBadges": "Badges completados",
  "areasWithCertifications": "Áreas con\ncertificaciones",
  "totalBadges": "Badges",
  "certificationsByArea": "Certificaciones por área",
  "noBadgesYet": "Sin badges aún",
  "monthApril": "Abril",
  "monthMay": "Mayo",
  "monthJune": "Junio",
  "monthJuly": "Julio",
  "monthAugust": "Agosto",
  "navExplore": "Explorar",
  "navBadges": "Badges",
  "navHome": "Inicio",
  "navProgress": "Evolución",
  "navProfile": "Perfil",
  "exploreCompetenciesTitle": "Explora nuevas competencias",
  "searchBadgeHint": "Busca tu badge",
  "noBadgesAvailable": "Sin badges disponibles.",
  "filtersAndSorting": "Filtros y ordenación",
  "sortBy": "Ordenar por",
  "sortMostRecent": "Más recientes",
  "sortOldest": "Más antiguos",
  "sortMostPoints": "Más puntos",
  "areaFrontend": "Frontend",
  "areaBackend": "Backend",
  "areaFullstack": "Fullstack",
  "areaAi": "IA",
  "levelBeginner": "Principiante",
  "levelIntermediate": "Intermedio",
  "levelExpert": "Experto",
  "badgeType": "Tipo de badge",
  "badgeTypeNormal": "Normal",
  "badgeTypeSpecial": "Especial",
  "last7Days": "Últimos 7 días",
  "last30Days": "Últimos 30 días",
  "thisYear": "Este año",
  "overviewTab": "Vista general",
  "detailsTab": "Detalles",
  "submitApplication": "Enviar candidatura",
  "applicationTitle": "Candidatura",
  "applicationSectionBadge": "Badge seleccionado",
  "applicationSectionEvidence": "Enviar evidencias",
  "applicationSectionTerms": "Términos y condiciones",
  "applicationSectionSubmission": "Envío",
  "applicationAttachFile": "Adjuntar archivo",
  "applicationAttachedFileSubtitle": "Asociado a todos los requisitos del badge",
  "noRequirementsLinked": "Sin requisito asociado.",
  "applicationSubmissionDisclaimer": "Al enviar esta candidatura, confirmas que las evidencias son verídicas y autorizas la validación por el equipo responsable.",
  "applicationStatusTitle": "Estado de la candidatura",
  "applicationStatusForBadge": "Candidatura al badge \"{badge}\"",
  "latestUpdates": "Últimas actualizaciones",
  "applicationInReviewBySll": "En revisión por el Service Line Leader",
  "applicationStatusTimestamp": "01/11/2025 a las 17:23",
  "talentManagerLabel": "Talent Manager",
  "applicationStatusPlaceholderNote": "Estamos validando las evidencias enviadas y confirmando la alineación con los requisitos del badge.",
  "attachedFiles": "Archivos adjuntos",
  "similarBadges": "Badges similares",
  "badgeInfo": "Información del badge",
  "stepSubmitted": "Enviado",
  "stepTm": "TM",
  "stepServiceLineLeader": "Service Line Leader",
  "validationNameRequired": "El nombre es obligatorio.",
  "validationNameMinChars": "El nombre debe tener al menos 2 caracteres.",
  "validationUsernameRequired": "El nombre de usuario es obligatorio.",
  "validationUsernameMinChars": "El nombre de usuario debe tener al menos 3 caracteres.",
  "validationUsernameInvalidChars": "El nombre de usuario solo puede contener letras, números, puntos y guiones bajos.",
  "validationEmailRequired": "El email es obligatorio.",
  "validationEmailInvalidFormat": "Formato de email no válido.",
  "validationPasswordRequired": "La contraseña es obligatoria.",
  "validationPasswordMinChars": "La contraseña debe tener al menos 8 caracteres.",
  "validationPasswordConfirmRequired": "Confirma la contraseña.",
  "validationPasswordConfirmMismatch": "Las contraseñas no coinciden.",
  "validationBirthdateFormat": "La fecha debe estar en formato dd/mm/aaaa.",
  "validationBiographyMaxChars": "La biografía debe tener como máximo 1000 caracteres.",
  "monthJanuary": "Enero",
  "monthFebruary": "Febrero",
  "monthMarch": "Marzo",
  "monthSeptember": "Septiembre",
  "monthOctober": "Octubre",
  "monthNovember": "Noviembre",
  "monthDecember": "Diciembre",
  "monthShortJan": "Ene",
  "monthShortFeb": "Feb",
  "monthShortMar": "Mar",
  "monthShortApr": "Abr",
  "monthShortMay": "May",
  "monthShortJun": "Jun",
  "monthShortJul": "Jul",
  "monthShortAug": "Ago",
  "monthShortSep": "Sep",
  "monthShortOct": "Oct",
  "monthShortNov": "Nov",
  "monthShortDec": "Dic",
  "editProfile": "Editar Perfil",
  "fullName": "Nombre completo",
  "biography": "Biografía",
  "biographyHint": "Escribe algo sobre ti...",
  "selectLocationLabel": "Seleccionar ubicación",
  "saveChanges": "Guardar Cambios",
  "profileUpdatedSuccess": "Perfil actualizado correctamente.",
  "profileUpdateError": "Error al actualizar perfil.",
  "pointsTitle": "Puntos",
  "pointsLabel": "puntos",
  "history": "Historial",
  "noPointsHistory": "Sin historial de puntos.",
  "topPercentMessage": "¡Estás en el top {percent}% de nuestros consultores!",
  "seeMore": "Ver más",
  "seeLess": "Ver menos",
  "weeklyPoints": "Puntos esta semana",
  "monthlyPoints": "Puntos por mes",
  "noDataAvailable": "Sin datos disponibles.",
  "badgesEarned": "badges conseguidos",
  "selectLanguageTitle": "Seleccionar idioma",
  "usernameUnavailable": "Nombre de usuario no disponible.",
  "usernameMinCharsEdit": "Mínimo de 3 caracteres.",
  "nameRequired": "El nombre es obligatorio.",
  "languageLabel": "Idioma",
  "goodMorning": "Buenos días",
  "goodAfternoon": "Buenas tardes",
  "goodEvening": "Buenas noches",
  "pwReqMinChars": "Mínimo de 8 caracteres",
  "pwReqUppercase": "Al menos 1 letra mayúscula",
  "pwReqLowercase": "Al menos 1 letra minúscula",
  "pwReqNumber": "Al menos 1 número",
  "pwReqSpecialChar": "Al menos 1 carácter especial (!@#$%^&*)",
  "loginErrorUserNotFound": "Usuario o email no encontrado.",
  "loginErrorWrongPassword": "Contraseña incorrecta.",
  "loginErrorAccountDeactivated": "Su cuenta ha sido desactivada. Contacte con el administrador.",
  "loginErrorAccountLocked": "Cuenta bloqueada por intentos excesivos. Inténtelo de nuevo en 15 minutos.",
  "rejectedByTM": "Rechazado por el Talent Manager",
  "rejectedBySL": "Rechazado por el Service Line Leader",
  "fileTooLarge": "El archivo es demasiado grande. El tamaño máximo permitido es {size} MB.",
  "fileUploadError": "No fue posible subir el archivo. Inténtalo de nuevo.",
  "downloadingFile": "Descargando archivo...",
  "fileDownloaded": "Archivo descargado correctamente.",
  "fileDownloadError": "No fue posible descargar el archivo.",
  "openingLink": "Abriendo enlace...",
  "certifiedCompetences": "Competencias Certificadas",
  "competenceCount_one": "competencia",
  "competenceCount_other": "competencias",
  "celebrationFirstBadgeTitle": "¡Primer Badge!",
  "celebrationFirstBadgeDesc": "¡Felicidades! Has conseguido tu primer badge. ¡Tu camino de certificaciones ha comenzado!",
  "celebration5BadgesTitle": "¡Estrella en Ascenso!",
  "celebration5BadgesDesc": "¡Increíble! Ya has conseguido 5 badges. ¡Estás construyendo un portafolio impresionante!",
  "celebration10BadgesTitle": "¡Coleccionista de Badges!",
  "celebration10BadgesDesc": "¡10 badges conseguidos! Tu dedicación está dando frutos. ¡Sigue así!",
  "celebration25BadgesTitle": "¡Especialista!",
  "celebration25BadgesDesc": "¡25 badges! Eres una referencia en el equipo. ¡Tu esfuerzo es inspirador!",
  "celebration50BadgesTitle": "¡Maestro de los Badges!",
  "celebration50BadgesDesc": "¡50 badges! Un logro extraordinario. ¡Eres un verdadero especialista de Softinsa!",
  "modelDownloadFailed": "No fue posible descargar el modelo de traducción. Verifica tu conexión a internet.",
  "tabEarnedBadges": "Badges Obtenidos",
  "tabApplications": "Candidaturas",
  "myBadgesSearchHint": "Buscar badges",
  "applicationsSearchHint": "Buscar candidaturas, badges",
  "noBadgesFound": "Ningún badge encontrado.",
  "noEarnedBadgesYet": "Aún no ha obtenido ningún badge.",
  "noApplicationsFound": "Ninguna candidatura encontrada.",
  "applicationsLoadFailedLocal": "No fue posible cargar candidaturas. Mostrando datos locales.",
  "filterAll": "Todos",
  "filterApproved": "Aprobadas",
  "filterInReview": "En revisión",
  "filterRejected": "Rechazadas",
  "stateApproved": "Aprobado",
  "stateRejected": "Rechazado",
  "stateInValidation": "En validación",
  "proofDocument": "Comprobante",
  "share": "Compartir",
  "special": "Especial",
  "expiresOn": "Expira el",
  "badgeSharedSuccess": "¡Badge compartido correctamente!",
  "couldNotOpenLink": "No fue posible abrir el enlace.",
  "couldNotIdentifyApplication": "No fue posible identificar la candidatura asociada a este badge.",
  "downloadingProof": "Descargando comprobante...",
  "proofDownloadError": "Error al descargar comprobante.",
  "gdprConsentError": "No fue posible registrar el consentimiento RGPD. Inténtelo de nuevo.",
  "approvedToday": "Aprobado hoy",
  "approvedOneDayAgo": "Aprobado hace 1 día",
  "approvedDaysAgo": "Aprobado hace {days} días",
  "shortTimeAgo": "hace un momento",
  "minutesAgo": "hace {minutes} minutos",
  "hoursAgo": "hace {hours} horas",
  "daysAgo": "hace {days} días",
  "consultantFallback": "Consultor",
  "userFallback": "Usuario",
  "primaryAreaNotDefined": "Área principal no definida",
  "technicalJourney": "Trayectoria Técnica",
  "badgesMetric": "Badges",
  "skillsMetric": "Competencias",
  "badgeGalleryTitle": "Galería de Badges",
  "badgeGallerySubtitle": "Ver y gestionar sus badges de logro",
  "galleryUpdateError": "No se pudo actualizar la galería. Inténtelo de nuevo.",
  "viewGallery": "Ver galería",
  "settings": "Ajustes",
  "myCharacteristics": "Mis características",
  "notificationPreferences": "Preferencias de notificaciones",
  "notificationChannelPush": "Notificaciones push",
  "notificationChannelEmail": "Email",
  "notificationPreferencesError": "No se pudieron actualizar las preferencias. Inténtelo de nuevo.",
  "notificationPreferencesEmpty": "No hay preferencias de notificaciones disponibles.",
  "changePasswordAction": "Cambiar contraseña",
  "emailSignature": "Firma de email",
  "languageChangeError": "Error al cambiar idioma.",
  "helpAndPolicies": "Ayuda y políticas",
  "privacyPolicies": "Políticas de privacidad",
  "termsAndConditionsTitle": "Términos y condiciones",
  "help": "Ayuda",
  "logout": "Cerrar sesión",
  "appVersion": "Versión {version}",
  "activeBadgesCount": "{count} activos",
  "noEvolutionData": "Sin datos de evolución.",
  "badgesByYear": "Badges por año",
  "evolutionGreeting": "¡Hola, {name}!",
  "badgesObtained": "Badges obtenidos",
  "activeAchievements": "Logros activos",
  "levelsCompleted": "Niveles completados",
  "totalPoints": "Puntos totales",
  "periodWeekly": "Semanal",
  "periodMonthly": "Mensual",
  "periodYearly": "Anual",
  "recentActivity": "Actividad reciente",
  "timeAgoValue": "Hace {time}",
  "applications": "Candidaturas",
  "approvalPercentage": "Porcentaje de aprobación",
  "submittedApplications": "Candidaturas realizadas",
  "learningPathProgress": "Progreso por Learning Path",
  "badgesPerArea": "Badges por área",

  "helpQuestionTitle": "¿Cómo puedo ayudarle?",
  "helpQuestionSubtitle": "Explore las funcionalidades de la aplicación y descubra cómo sacar el mejor partido de la plataforma.",
  "helpFeatures": "Funcionalidades",
  "helpDashboardTitle": "Dashboard",
  "helpDashboardDesc": "El Dashboard es su página de inicio. Aquí puede ver un resumen de sus actividades, anuncios recientes, su progreso y el ranking general de la plataforma.",
  "helpExploreTitle": "Explorar Competencias",
  "helpExploreDesc": "En esta sección puede navegar por todos los badges disponibles en la plataforma. Utilice los filtros para buscar por área, nivel, puntos o fecha. Toque un badge para ver los detalles e iniciar una candidatura.",
  "helpMyBadgesTitle": "Mis Badges",
  "helpMyBadgesDesc": "Consulte los badges que ya ha obtenido en la pestaña \"Badges Obtenidos\" y siga el estado de sus candidaturas en la pestaña \"Candidaturas\". Puede compartir o descargar badges obtenidos.",
  "helpEvolutionTitle": "Evolución",
  "helpEvolutionDesc": "La sección de Evolución muestra su progreso a lo largo del tiempo: puntos acumulados, badges conseguidos y su posición en el ranking. Siga el crecimiento de su trayectoria técnica.",
  "helpProfileTitle": "Perfil",
  "helpProfileDesc": "En su perfil puede ver y editar su información personal, cambiar el idioma de la aplicación, consultar sus características, gestionar la firma de email y acceder a los ajustes de la cuenta.",
  "helpApplicationsTitle": "Candidaturas",
  "helpApplicationsDesc": "Para obtener un badge, inicie una candidatura en la página de detalles del badge. Adjunte las evidencias necesarias (archivos, certificados) y envíe. La candidatura será evaluada por el Talent Manager y después por el Service Line Leader.",
  "helpNotificationsTitle": "Notificaciones",
  "helpNotificationsDesc": "Reciba alertas sobre el estado de sus candidaturas, badges a punto de expirar y otras actualizaciones relevantes. Puede marcar notificaciones como leídas individualmente o todas a la vez.",
  "helpShareTitle": "Compartir Badges",
  "helpShareDesc": "Tras obtener un badge, puede compartirlo públicamente. En la primera vez que comparta se solicitará el consentimiento RGPD. Los badges compartidos son accesibles a través de un enlace público de verificación.",

  "iAmIntro": "Yo {name} soy",
  "noCharacteristicsDefined": "Aún sin características definidas.",

  "selectBadgesToShow": "Seleccione los Badges a mostrar",
  "recentFilter": "Recientes",
  "previewLabel": "Vista previa",
  "previewBefore": "Antes",
  "previewAfter": "Después",
  "noBadgeSelected": "Ningún badge seleccionado",
  "confirmEmailSignatureAction": "Confirmar Firma de email",
  "saveAndSendSignature": "Guardar y enviar su firma",
  "selectAtLeastOneBadge": "Seleccione al menos un badge.",
  "emailSignatureSaved": "Firma de email guardada correctamente.",
  "emailSignatureSaveError": "Error al guardar la firma de email.",

  "welcomeFirstLogin": "¡Bienvenido!",
  "firstLoginPasswordPrompt": "Por seguridad, establezca una nueva contraseña para su cuenta.",
  "currentPassword": "Contraseña actual",
  "newPassword": "Nueva contraseña",
  "enterCurrentPassword": "Introduzca la contraseña actual.",
  "changePasswordButton": "Cambiar Contraseña",
  "changePasswordSuccess": "Contraseña cambiada correctamente.",
  "changePasswordErrorGeneric": "Error al cambiar contraseña.",
  "errorCurrentPasswordWrong": "La contraseña actual es incorrecta. Verifique e inténtelo de nuevo.",
  "errorPasswordFormatInvalid": "La nueva contraseña no cumple los requisitos de seguridad.",
  "errorPasswordSameAsCurrent": "La nueva contraseña no puede ser igual a la contraseña actual.",

  "applicationStartError": "Error al iniciar candidatura.",
  "applicationExistsInState": "Ya existe una candidatura en estado \"{state}\" para este badge.",
  "applicationGuidError": "Error: GUID de la candidatura no recibido.",
  "applicationSubmitError": "Error al enviar candidatura.",
  "submitting": "Enviando...",

  "applicationSubmitted": "Candidatura enviada",
  "applicationReceivedSuccess": "¡Su candidatura fue recibida correctamente!",
  "badgeTypeLabel": "Tipo de Badge",
  "submittedAtLabel": "Enviada el",
  "confirmationSentTo": "Confirmación enviada a",
  "nextSteps": "Próximos pasos",
  "nextStepEvaluation": "La candidatura será evaluada",
  "nextStepResult": "Recibirá un resultado en aproximadamente 5 días",
  "viewApplicationStatus": "Ver estado de la candidatura",
  "backToMenu": "Volver al Menú",

  "confirmYourApplication": "Confirme su candidatura",
  "applicationSubmittedSuccess": "¡Su candidatura fue enviada correctamente!",
  "sendConfirmationInstruction": "Para finalizar, envíe el email de confirmación de su candidatura para el badge:",
  "sending": "Enviando...",
  "sendConfirmationEmail": "Enviar email de confirmación",
  "emailResendUnavailable": "El reenvío de email no está disponible en este momento. El email original fue enviado con el envío.",
  "emailSendError": "Error al enviar email de confirmación.",
  "emailResendFailed": "No fue posible reenviar el email. Inténtelo más tarde.",
  "confirmationEmailSentTo": "Hemos enviado un email de confirmación a:",
  "applicationWillBeEvaluated": "Su candidatura será evaluada por el Talent Manager y el Service Line Leader. Recibirá una notificación con el resultado.",
  "resendEmailCooldown": "Reenviar email ({seconds} s)",
  "resendEmail": "Reenviar email",
  "emailNotReceived": "¿No recibió el email? Revise su carpeta de spam.",

  "applicationApprovedSuccess": "¡Candidatura aprobada correctamente!",
  "inReviewBySLL": "En revisión por el Service Line Leader",
  "inReviewByTM": "En revisión por el Talent Manager",
  "applicationOpen": "Candidatura abierta",
  "progress": "Progreso",
  "stepSubmittedLabel": "Enviado",
  "stepApprovedLabel": "Aprobado",
  "details": "Detalles",
  "openedAt": "Abierta el",
  "observation": "Observación",
  "badgeInformation": "Información del badge",
  "createdAt": "Creado el",
  "validityDays": "Validez: {days} días",
  "applicationDetails": "Detalles de la candidatura",
  "applicationSubmittedDialog": "¡Candidatura enviada!",
  "applicationSubmittedDialogDesc": "Su candidatura fue enviada correctamente y será evaluada en breve.",
  "viewApplication": "Ver candidatura",
  "viewBadges": "Ver badges",

  "stateApprovedF": "Aprobada",
  "stateRejectedF": "Rechazada",
  "stateInValidationF": "En validación",
  "stateSubmittedF": "Enviada",
  "stateInAnalysis": "En revisión",
  "badgeSaved": "¡Badge guardado!",
  "badgeUnsaved": "Badge eliminado de guardados.",
  "linkCopied": "¡Enlace copiado al portapapeles!",
  "estimatedDuration": "Duración estimada",
  "duration": "Duración",
  "validity": "Validez",
  "markAsRead": "Marcar como leída",
  "timeNow": "Ahora",
  "notifTypeHome": "Inicio",
  "notifTypeBadges": "Badges",
  "notifTypeApplications": "Candidaturas",
  "notifTypeAchievements": "Logros",
  "notifTypePoints": "Puntos",
  "notifTypeObjectives": "Objetivos",
  "notifTypeEvolution": "Evolución",
  "notifTypeAnnouncements": "Anuncios",
  "notifTypeSystem": "Sistema",
  "notifApplicationSubmitted": "Candidatura Enviada",
  "notifApprovedByTm": "Aprobado por el Talent Manager",
  "notifBadgeAccepted": "Badge Aceptado",
  "notifApplicationRejected": "Candidatura Rechazada",
  "notifApproved": "Aprobado",
  "notifRejected": "Rechazado",
  "notifExpiration": "Expiración",
  "notifGeneric": "Notificación",
  "completed": "Completado",
  "primary": "Principal",
  "addAsGoal": "Añadir como objetivo",
  "goalAdded": "¡Badge añadido como objetivo!",
  "goalAddError": "Error al añadir objetivo.",
  "copyHtmlCode": "Copiar código",
  "htmlCopied": "¡Código copiado!",
  "emailSignatureInstructions": "Instrucciones",
  "gmailInstructions": "Gmail: Configuración → Ver toda la configuración → General → Firma → Pegue el código",
  "outlookInstructions": "Outlook: Archivo → Opciones → Correo → Firmas → Nueva → Pegue el código",
  "serviceLine": "Service Line",
  "learningPath": "Learning Path",
  "badgeType": "Tipo",
  "removeGoal": "Eliminar objetivo",
  "removing": "Eliminando...",
  "goalRemoved": "Objetivo eliminado.",
  "cancel": "Cancelar",
  "confirm": "Confirmar",
  "confirmConclusion": "Completar objetivo",
  "concluding": "Concluyendo...",
  "goalConcluded": "¡Objetivo completado!",
  "goalNotOwned": "Aún no has conseguido este badge.",
  "goalCompleteError": "No se pudo completar el objetivo.",
  "goalDeadlineTitle": "Definir plazo del objetivo",
  "goalDeadlineSubtitle": "Elige en cuántos meses quieres completar este objetivo.",
  "goalDeadlinePreview": "Plazo: {date}",
  "durationMonth": "mes",
  "durationMonths": "meses",
  "NOTIF_APP_SUBMITTED_TITLE": "Candidatura enviada",
  "NOTIF_APP_SUBMITTED_BODY": "Tu candidatura para el badge \"{{badgeTitle}}\" fue enviada con éxito.",
  "NOTIF_APP_NEW_APPLICATION_TITLE": "Nueva candidatura recibida",
  "NOTIF_APP_NEW_APPLICATION_BODY": "Una nueva candidatura para el badge \"{{badgeTitle}}\" está pendiente de revisión.",
  "NOTIF_APP_BADGE_AWARDED_TITLE": "Badge otorgado",
  "NOTIF_APP_BADGE_AWARDED_BODY": "¡Felicidades! El badge \"{{badgeTitle}}\" te ha sido otorgado.",
  "NOTIF_APP_SPECIAL_BADGE_AWARDED_TITLE": "Badge especial otorgado",
  "NOTIF_APP_SPECIAL_BADGE_AWARDED_BODY": "¡Felicidades! El badge especial \"{{badgeTitle}}\" te ha sido otorgado.",
  "NOTIF_APP_REJECTED_TITLE": "Candidatura rechazada",
  "NOTIF_APP_REJECTED_BODY": "Tu candidatura para el badge \"{{badgeTitle}}\" ha sido rechazada.",
  "NOTIF_APP_IN_VALIDATION_TITLE": "Candidatura en validación",
  "NOTIF_APP_IN_VALIDATION_BODY": "Tu candidatura para el badge \"{{badgeTitle}}\" está ahora en validación.",
  "NOTIF_APP_PENDING_SLL_REVIEW_TITLE": "Candidatura pendiente de revisión",
  "NOTIF_APP_PENDING_SLL_REVIEW_BODY": "Una candidatura para el badge \"{{badgeTitle}}\" está pendiente de tu revisión.",
  "NOTIF_BADGE_EXPIRING_SOON_TITLE": "Badge a punto de expirar",
  "NOTIF_BADGE_EXPIRING_SOON_BODY": "Tu badge \"{{badgeTitle}}\" expira en {{daysRemaining}} días.",
  "NOTIF_BADGE_EXPIRED_TITLE": "Badge expirado",
  "NOTIF_BADGE_EXPIRED_BODY": "Tu badge \"{{badgeTitle}}\" ha expirado.",
  "NOTIF_SLA_BREACH_TITLE": "Incumplimiento de SLA",
  "NOTIF_SLA_BREACH_BODY": "El SLA \"{{slaName}}\" fue superado en {{hoursExceeded}}h para el badge \"{{badgeTitle}}\".",
  "NOTIF_CUSTOM_SLA_BREACH_TITLE": "Incumplimiento de SLA personalizado",
  "NOTIF_CUSTOM_SLA_BREACH_BODY": "El SLA \"{{slaName}}\" ha alcanzado su plazo límite.",
  "NOTIF_GOAL_REMINDER_TITLE": "Recordatorio de objetivo",
  "NOTIF_GOAL_REMINDER_BODY": "No olvides tu objetivo \"{{goalTitle}}\".",
  "NOTIF_GOAL_DEADLINE_APPROACHING_TITLE": "Plazo de objetivo próximo",
  "NOTIF_GOAL_DEADLINE_APPROACHING_BODY": "Tu objetivo \"{{goalTitle}}\" vence en {{daysRemaining}} días.",

  "policyTypePrivacy": "Política de Privacidad",
  "policyTypeTerms": "Términos y Condiciones",
  "policyTypeCookies": "Política de Cookies",

  "includeOptions": "Incluir",
  "includePhoto": "Incluir foto",
  "includeName": "Incluir nombre",
  "viewSignature": "Ver firma",
  "viewEmailTemplate": "Ver plantilla de correo",
  "copySignature": "Copiar firma",
  "copyEmailTemplate": "Copiar plantilla de correo",
  "signatureNoBadgesNote": "Solo los consultores pueden incluir badges en la firma de correo.",
  "roleConsultant": "Consultor",
  "roleTalentManager": "Talent Manager",
  "roleServiceLineLeader": "Service Line Leader",
  "roleAdministrator": "Administrador",

  "emailConfirmationTitle": "¡Email enviado!",
  "emailConfirmationSentTo": "Hemos enviado un email de confirmación a:",
  "emailConfirmationInstructions": "Haga clic en el enlace enviado a su email para activar su cuenta. Después de la confirmación, podrá iniciar sesión en la aplicación.",
  "goToLogin": "Ir al inicio de sesión",
  "resendConfirmationBtn": "Reenviar email",
  "resendConfirmationCooldown": "Reenviar email ({seconds} s)",
  "resendConfirmationError": "Error al reenviar el email de confirmación.",
  "resendConfirmationErrorRetry": "Error al reenviar email. Inténtelo de nuevo.",
  "checkSpamHint": "¿No recibió el email? Revise su carpeta de spam o intente reenviar.",
  "rateLimitedRetry": "Espere {seconds} segundos antes de intentarlo de nuevo.",

  "resetPasswordTitle": "Restablecer contraseña",
  "resetPasswordSubtitle": "Introduzca su nueva contraseña.",
  "validatingLink": "Validando enlace...",
  "invalidOrExpiredTitle": "Enlace inválido o expirado",
  "invalidOrExpiredDesc": "El enlace de restablecimiento de contraseña es inválido o ha expirado. Solicite un nuevo enlace.",
  "tokenExpired": "El enlace ha expirado. Solicite un nuevo enlace de restablecimiento.",
  "requestNewLink": "Solicitar nuevo enlace",
  "confirmNewPassword": "Confirmar nueva contraseña",
  "resetPasswordBtn": "Restablecer contraseña",
  "resetPasswordSuccess": "¡Contraseña restablecida!",
  "resetPasswordSuccessDesc": "Su contraseña se ha restablecido correctamente. Ahora puede iniciar sesión con su nueva contraseña.",

  "confirmingEmail": "Confirmando su email...",
  "emailConfirmedTitle": "¡Email confirmado!",
  "emailConfirmedDesc": "Su email se ha confirmado correctamente. Ahora puede iniciar sesión en la aplicación.",
  "confirmationFailed": "Confirmación fallida",
  "confirmationFailedDesc": "No fue posible confirmar su email. El enlace puede ser inválido o haber expirado.",

  "loginErrorConsultantOnly": "Solo las cuentas de Consultores pueden acceder a la aplicación móvil.",
  "loginErrorEmailNotConfirmed": "Su email aún no ha sido confirmado. Revise su bandeja de entrada.",

  "storeTitle": "Tienda de Recompensas",
  "storeSubtitle": "Gaste sus puntos en cursos y beneficios.",
  "storePoints": "puntos",
  "storeRedeem": "Canjear",
  "storeNotEnough": "Puntos insuficientes",
  "storeEmpty": "Aún no hay recompensas disponibles.",
  "storeMyRedemptions": "Mis canjes",
  "storeAccess": "Acceder",
  "storeConfirmTitle": "Confirmar canje",
  "storeConfirmText": "¿Canjear \"{name}\" por {cost} puntos?",
  "storeSuccessTitle": "¡Recompensa canjeada!",
  "storeSuccessText": "Ha canjeado \"{name}\" con éxito.",
  "storeEmailNote": "Le hemos enviado los detalles de acceso por email.",
  "storeMyTitle": "Mi título",
  "storeMyTitleHint": "Elija el título mostrado públicamente en su perfil (de los que ha desbloqueado).",
  "storeNoTitle": "Ninguno",
  "storeRewardsStore": "Tienda de Recompensas",
  "storeSpendPoints": "Gastar puntos"
}
''';
