import 'dart:ui';

class AppStrings {
  static const String defaultLanguageCode = '1';

  static const List<String> supportedLanguageCodes = ['1', '2', '3', '4'];

  static const Map<String, Locale> _locales = {
    '1': Locale('pt'),
    '2': Locale('en'),
    '3': Locale('es'),
    '4': Locale('fr'),
  };

  static Locale localeForCode(String code) {
    return _locales[code] ?? _locales[defaultLanguageCode]!;
  }

  static String languageName(String code) {
    switch (code) {
      case '2':
        return 'English';
      case '3':
        return 'Espanol';
      case '4':
        return 'Francais';
      case '1':
      default:
        return 'Portugues';
    }
  }

  static String translate(String code, String key) {
    final localized = _translations[code];
    final fallback = _translations[defaultLanguageCode]!;
    return localized?[key] ?? fallback[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    '1': {
      'appTitle': 'Softinsa - Autenticacao',
      'loading': 'A carregar...',
      'createAccount': 'Criar Conta',
      'registerTitle': 'Crie sua conta',
      'registerSubtitle': 'Junte-se a Softinsa',
      'name': 'Nome Completo',
      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirmar Password',
      'optionalFields': 'Campos opcionais',
      'phone': 'Telemovel',
      'invalidPhone': 'Telemovel invalido',
      'birthdate': 'Data de Nascimento',
      'profileImage': 'Imagem de Perfil',
      'noFileSelected': 'Nenhum ficheiro selecionado',
      'pickFromPhone': 'Escolher do telemovel',
      'location': 'Localidade',
      'selectLocation': 'Selecionar localidade',
      'preferredLanguageOptional': 'Linguagem Preferida (Opcional)',
      'aboutMe': 'Sobre mim',
      'aboutMeHint': 'Escreva uma breve biografia',
      'acceptTermsPrefix': 'Eu aceito os ',
      'termsAndConditions': 'Termos e Condicoes',
      'finishRegister': 'Concluir registo',
      'alreadyHaveAccount': 'Ja tem conta?',
      'doLogin': 'Fazer login',
      'mustAcceptTerms': 'Voce deve aceitar os termos para continuar',
      'accountCreatedWithEmail': 'Conta criada com sucesso! Email: {email}',
      'selectAreasDescription': 'Para prosseguir, selecione as suas areas de interesse (ate 5). A primeira area escolhida sera automaticamente a area principal.',
      'chooseMainArea': 'Escolha a area principal',
      'back': 'Voltar',
      'maxFiveAreas': 'Pode selecionar no maximo 5 areas.',
      'welcomeBack': 'Bem-vindo de volta',
      'loginSubtitle': 'Faca login na sua conta',
      'emailOrUsername': 'Email ou username',
      'emailOrUsernameHint': 'seu.email@softinsa.com ou joaosilva',
      'emailOrUsernameRequired': 'Email ou username e obrigatorio',
      'usernameMinChars': 'Username deve ter no minimo 3 caracteres',
      'enterPasswordHint': 'Insira sua password',
      'saveLoginData': 'Guardar dados de login',
      'forgotPassword': 'Esqueci-me da password',
      'login': 'Entrar',
      'noAccount': 'Nao tem conta?',
      'register': 'Criar conta',
      'loginSuccess': 'Login bem-sucedido! Utilizador: {user}',
      'recoverPassword': 'Recuperar Password',
      'recoverSubtitle': 'Insira seu email para receber instrucoes',
      'sendInstructions': 'Enviar Instrucoes',
      'emailSentTo': 'Instrucoes enviadas para {email}',
      'emailSent': 'Email Enviado!',
      'checkMailbox': 'Verifique sua caixa de correio para as instrucoes de recuperacao de password.',
      'backToLogin': 'Voltar para Login',
      'didNotReceiveEmail': 'Nao recebeu o email?',
      'checkSpam': 'Verifique a pasta de spam ou tente novamente com outro email.',
      'confirmRegister': 'Confirmar Registo',
      'registerSummary': 'Resumo do Registo',
      'personalData': 'Dados Pessoais',
      'selectedAreas': 'Areas de Interesse',
      'mainArea': 'Area Principal',
      'noneSelectedArea': 'Nenhuma area selecionada',
      'registerUser': 'Registar Utilizador',
      'notFilled': '(nao preenchido)',
      'notFilledF': '(nao preenchida)',
      'notDefined': '(nao definida)',
      'userRegisteredSuccess': 'Utilizador {username} registado com sucesso!',
      'emailRequired': 'O email e obrigatorio',
      'emailMax': 'O email deve ter no maximo 255 caracteres',
      'emailInvalid': 'Por favor, insira um email valido',
      'passwordRequired': 'A password e obrigatoria',
      'passwordMin': 'A password deve ter no minimo 8 caracteres',
      'passwordMax': 'A password deve ter no maximo 100 caracteres',
      'passwordUpper': 'A password deve conter pelo menos 1 letra maiuscula',
      'passwordLower': 'A password deve conter pelo menos 1 letra minuscula',
      'passwordNumber': 'A password deve conter pelo menos 1 numero',
      'passwordSpecial': 'A password deve conter pelo menos 1 caractere especial',
      'confirmPasswordRequired': 'Por favor, confirme a password',
      'passwordMismatch': 'As passwords nao coincidem',
      'nameRequired': 'O nome e obrigatorio',
      'nameMin': 'O nome deve ter pelo menos 2 caracteres',
      'nameMax': 'O nome deve ter no maximo 255 caracteres',
      'usernameRequired': 'Username e obrigatorio',
      'usernameMax': 'Username deve ter no maximo 50 caracteres',
      'usernameFormat': 'Username so pode conter letras, numeros, ponto e underscore',
      'bioMaxChars': 'Biografia deve ter no maximo 5000 caracteres',
      'bioMaxWords': 'Biografia nao pode exceder 500 palavras',
      'bioInappropriate': 'Biografia contem linguagem inapropriada',
      'birthdateRequired': 'A data de nascimento e obrigatoria',
      'birthdateInvalid': 'Data de nascimento invalida',
      'mustBe16': 'Tens de ter pelo menos 16 anos'
    },
    '2': {
      'appTitle': 'Softinsa - Authentication',
      'loading': 'Loading...',
      'createAccount': 'Create Account',
      'registerTitle': 'Create your account',
      'registerSubtitle': 'Join Softinsa',
      'name': 'Full Name',
      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'optionalFields': 'Optional fields',
      'phone': 'Phone',
      'invalidPhone': 'Invalid phone number',
      'birthdate': 'Birthdate',
      'profileImage': 'Profile Image',
      'noFileSelected': 'No file selected',
      'pickFromPhone': 'Choose from phone',
      'location': 'Location',
      'selectLocation': 'Select location',
      'preferredLanguageOptional': 'Preferred Language (Optional)',
      'aboutMe': 'About me',
      'aboutMeHint': 'Write a short biography',
      'acceptTermsPrefix': 'I accept the ',
      'termsAndConditions': 'Terms and Conditions',
      'finishRegister': 'Finish registration',
      'alreadyHaveAccount': 'Already have an account?',
      'doLogin': 'Login',
      'mustAcceptTerms': 'You must accept the terms to continue',
      'accountCreatedWithEmail': 'Account created successfully! Email: {email}',
      'selectAreasDescription': 'To continue, select your interest areas (up to 5). The first selected area is automatically set as the main area.',
      'chooseMainArea': 'Choose main area',
      'back': 'Back',
      'maxFiveAreas': 'You can select at most 5 areas.',
      'welcomeBack': 'Welcome back',
      'loginSubtitle': 'Sign in to your account',
      'emailOrUsername': 'Email or username',
      'emailOrUsernameHint': 'your.email@softinsa.com or johndoe',
      'emailOrUsernameRequired': 'Email or username is required',
      'usernameMinChars': 'Username must have at least 3 characters',
      'enterPasswordHint': 'Enter your password',
      'saveLoginData': 'Remember login data',
      'forgotPassword': 'Forgot password',
      'login': 'Sign in',
      'noAccount': 'No account yet?',
      'register': 'Create account',
      'loginSuccess': 'Login successful! User: {user}',
      'recoverPassword': 'Recover Password',
      'recoverSubtitle': 'Enter your email to receive instructions',
      'sendInstructions': 'Send Instructions',
      'emailSentTo': 'Instructions sent to {email}',
      'emailSent': 'Email Sent!',
      'checkMailbox': 'Check your mailbox for password recovery instructions.',
      'backToLogin': 'Back to Login',
      'didNotReceiveEmail': 'Did not receive the email?',
      'checkSpam': 'Check the spam folder or try again with another email.',
      'confirmRegister': 'Confirm Registration',
      'registerSummary': 'Registration Summary',
      'personalData': 'Personal Data',
      'selectedAreas': 'Interest Areas',
      'mainArea': 'Main Area',
      'noneSelectedArea': 'No selected areas',
      'registerUser': 'Register User',
      'notFilled': '(not filled)',
      'notFilledF': '(not filled)',
      'notDefined': '(not defined)',
      'userRegisteredSuccess': 'User {username} registered successfully!',
      'emailRequired': 'Email is required',
      'emailMax': 'Email must be at most 255 characters',
      'emailInvalid': 'Please enter a valid email',
      'passwordRequired': 'Password is required',
      'passwordMin': 'Password must be at least 8 characters',
      'passwordMax': 'Password must be at most 100 characters',
      'passwordUpper': 'Password must contain at least 1 uppercase letter',
      'passwordLower': 'Password must contain at least 1 lowercase letter',
      'passwordNumber': 'Password must contain at least 1 number',
      'passwordSpecial': 'Password must contain at least 1 special character',
      'confirmPasswordRequired': 'Please confirm the password',
      'passwordMismatch': 'Passwords do not match',
      'nameRequired': 'Name is required',
      'nameMin': 'Name must be at least 2 characters',
      'nameMax': 'Name must be at most 255 characters',
      'usernameRequired': 'Username is required',
      'usernameMax': 'Username must be at most 50 characters',
      'usernameFormat': 'Username can only contain letters, numbers, dot and underscore',
      'bioMaxChars': 'Biography must be at most 5000 characters',
      'bioMaxWords': 'Biography cannot exceed 500 words',
      'bioInappropriate': 'Biography contains inappropriate language',
      'birthdateRequired': 'Birthdate is required',
      'birthdateInvalid': 'Invalid birthdate',
      'mustBe16': 'You must be at least 16 years old'
    },
    '3': {
      'appTitle': 'Softinsa - Autenticacion',
      'loading': 'Cargando...',
      'createAccount': 'Crear cuenta',
      'registerTitle': 'Crea tu cuenta',
      'registerSubtitle': 'Unete a Softinsa',
      'name': 'Nombre completo',
      'username': 'Usuario',
      'email': 'Correo',
      'password': 'Contrasena',
      'confirmPassword': 'Confirmar contrasena',
      'optionalFields': 'Campos opcionales',
      'phone': 'Telefono',
      'invalidPhone': 'Telefono invalido',
      'birthdate': 'Fecha de nacimiento',
      'profileImage': 'Imagen de perfil',
      'noFileSelected': 'Ningun archivo seleccionado',
      'pickFromPhone': 'Elegir del telefono',
      'location': 'Localidad',
      'selectLocation': 'Seleccionar localidad',
      'preferredLanguageOptional': 'Idioma preferido (Opcional)',
      'aboutMe': 'Sobre mi',
      'aboutMeHint': 'Escribe una breve biografia',
      'acceptTermsPrefix': 'Acepto los ',
      'termsAndConditions': 'Terminos y condiciones',
      'finishRegister': 'Finalizar registro',
      'alreadyHaveAccount': 'Ya tienes cuenta?',
      'doLogin': 'Iniciar sesion',
      'mustAcceptTerms': 'Debes aceptar los terminos para continuar',
      'accountCreatedWithEmail': 'Cuenta creada con exito. Email: {email}',
      'selectAreasDescription': 'Para continuar, selecciona tus areas de interes (hasta 5). La primera area seleccionada se define automaticamente como area principal.',
      'chooseMainArea': 'Elegir area principal',
      'back': 'Volver',
      'maxFiveAreas': 'Puedes seleccionar como maximo 5 areas.',
      'welcomeBack': 'Bienvenido de nuevo',
      'loginSubtitle': 'Inicia sesion en tu cuenta',
      'emailOrUsername': 'Correo o usuario',
      'emailOrUsernameHint': 'tu.correo@softinsa.com o usuario',
      'emailOrUsernameRequired': 'Correo o usuario es obligatorio',
      'usernameMinChars': 'El usuario debe tener al menos 3 caracteres',
      'enterPasswordHint': 'Introduce tu contrasena',
      'saveLoginData': 'Guardar datos de inicio',
      'forgotPassword': 'Olvide mi contrasena',
      'login': 'Entrar',
      'noAccount': 'No tienes cuenta?',
      'register': 'Crear cuenta',
      'loginSuccess': 'Inicio correcto. Usuario: {user}',
      'recoverPassword': 'Recuperar contrasena',
      'recoverSubtitle': 'Introduce tu correo para recibir instrucciones',
      'sendInstructions': 'Enviar instrucciones',
      'emailSentTo': 'Instrucciones enviadas a {email}',
      'emailSent': 'Correo enviado!',
      'checkMailbox': 'Revisa tu correo para las instrucciones de recuperacion.',
      'backToLogin': 'Volver al inicio',
      'didNotReceiveEmail': 'No recibiste el correo?',
      'checkSpam': 'Revisa la carpeta de spam o prueba con otro correo.',
      'confirmRegister': 'Confirmar registro',
      'registerSummary': 'Resumen del registro',
      'personalData': 'Datos personales',
      'selectedAreas': 'Areas de interes',
      'mainArea': 'Area principal',
      'noneSelectedArea': 'Ninguna area seleccionada',
      'registerUser': 'Registrar usuario',
      'notFilled': '(no completado)',
      'notFilledF': '(no completada)',
      'notDefined': '(no definida)',
      'userRegisteredSuccess': 'Usuario {username} registrado con exito',
      'emailRequired': 'El correo es obligatorio',
      'emailMax': 'El correo debe tener como maximo 255 caracteres',
      'emailInvalid': 'Por favor, introduce un correo valido',
      'passwordRequired': 'La contrasena es obligatoria',
      'passwordMin': 'La contrasena debe tener al menos 8 caracteres',
      'passwordMax': 'La contrasena debe tener como maximo 100 caracteres',
      'passwordUpper': 'La contrasena debe contener al menos 1 mayuscula',
      'passwordLower': 'La contrasena debe contener al menos 1 minuscula',
      'passwordNumber': 'La contrasena debe contener al menos 1 numero',
      'passwordSpecial': 'La contrasena debe contener al menos 1 caracter especial',
      'confirmPasswordRequired': 'Por favor, confirma la contrasena',
      'passwordMismatch': 'Las contrasenas no coinciden',
      'nameRequired': 'El nombre es obligatorio',
      'nameMin': 'El nombre debe tener al menos 2 caracteres',
      'nameMax': 'El nombre debe tener como maximo 255 caracteres',
      'usernameRequired': 'El usuario es obligatorio',
      'usernameMax': 'El usuario debe tener como maximo 50 caracteres',
      'usernameFormat': 'El usuario solo puede contener letras, numeros, punto y guion bajo',
      'bioMaxChars': 'La biografia debe tener como maximo 5000 caracteres',
      'bioMaxWords': 'La biografia no puede superar 500 palabras',
      'bioInappropriate': 'La biografia contiene lenguaje inapropiado',
      'birthdateRequired': 'La fecha de nacimiento es obligatoria',
      'birthdateInvalid': 'Fecha de nacimiento invalida',
      'mustBe16': 'Debes tener al menos 16 anos'
    },
    '4': {
      'appTitle': 'Softinsa - Authentification',
      'loading': 'Chargement...',
      'createAccount': 'Creer un compte',
      'registerTitle': 'Creez votre compte',
      'registerSubtitle': 'Rejoignez Softinsa',
      'name': 'Nom complet',
      'username': 'Nom utilisateur',
      'email': 'Email',
      'password': 'Mot de passe',
      'confirmPassword': 'Confirmer le mot de passe',
      'optionalFields': 'Champs optionnels',
      'phone': 'Telephone',
      'invalidPhone': 'Telephone invalide',
      'birthdate': 'Date de naissance',
      'profileImage': 'Image de profil',
      'noFileSelected': 'Aucun fichier selectionne',
      'pickFromPhone': 'Choisir depuis le telephone',
      'location': 'Localite',
      'selectLocation': 'Selectionner la localite',
      'preferredLanguageOptional': 'Langue preferee (Optionnel)',
      'aboutMe': 'A propos de moi',
      'aboutMeHint': 'Ecrivez une breve biographie',
      'acceptTermsPrefix': 'J accepte les ',
      'termsAndConditions': 'Termes et conditions',
      'finishRegister': 'Finaliser l inscription',
      'alreadyHaveAccount': 'Vous avez deja un compte?',
      'doLogin': 'Connexion',
      'mustAcceptTerms': 'Vous devez accepter les termes pour continuer',
      'accountCreatedWithEmail': 'Compte cree avec succes! Email: {email}',
      'selectAreasDescription': 'Pour continuer, selectionnez vos domaines d interet (jusqu a 5). Le premier domaine selectionne est automatiquement defini comme domaine principal.',
      'chooseMainArea': 'Choisir le domaine principal',
      'back': 'Retour',
      'maxFiveAreas': 'Vous pouvez selectionner au maximum 5 domaines.',
      'welcomeBack': 'Bon retour',
      'loginSubtitle': 'Connectez-vous a votre compte',
      'emailOrUsername': 'Email ou nom utilisateur',
      'emailOrUsernameHint': 'votre.email@softinsa.com ou utilisateur',
      'emailOrUsernameRequired': 'Email ou nom utilisateur obligatoire',
      'usernameMinChars': 'Le nom utilisateur doit avoir au moins 3 caracteres',
      'enterPasswordHint': 'Entrez votre mot de passe',
      'saveLoginData': 'Memoriser les donnees de connexion',
      'forgotPassword': 'Mot de passe oublie',
      'login': 'Se connecter',
      'noAccount': 'Pas de compte?',
      'register': 'Creer un compte',
      'loginSuccess': 'Connexion reussie! Utilisateur: {user}',
      'recoverPassword': 'Recuperer le mot de passe',
      'recoverSubtitle': 'Entrez votre email pour recevoir les instructions',
      'sendInstructions': 'Envoyer les instructions',
      'emailSentTo': 'Instructions envoyees a {email}',
      'emailSent': 'Email envoye!',
      'checkMailbox': 'Verifiez votre boite mail pour les instructions.',
      'backToLogin': 'Retour a la connexion',
      'didNotReceiveEmail': 'Vous n avez pas recu l email?',
      'checkSpam': 'Verifiez le dossier spam ou reessayez avec un autre email.',
      'confirmRegister': 'Confirmer l inscription',
      'registerSummary': 'Resume de l inscription',
      'personalData': 'Donnees personnelles',
      'selectedAreas': 'Domaines d interet',
      'mainArea': 'Domaine principal',
      'noneSelectedArea': 'Aucun domaine selectionne',
      'registerUser': 'Enregistrer utilisateur',
      'notFilled': '(non renseigne)',
      'notFilledF': '(non renseignee)',
      'notDefined': '(non definie)',
      'userRegisteredSuccess': 'Utilisateur {username} enregistre avec succes!',
      'emailRequired': 'L email est obligatoire',
      'emailMax': 'L email doit contenir au maximum 255 caracteres',
      'emailInvalid': 'Veuillez saisir un email valide',
      'passwordRequired': 'Le mot de passe est obligatoire',
      'passwordMin': 'Le mot de passe doit avoir au moins 8 caracteres',
      'passwordMax': 'Le mot de passe doit avoir au maximum 100 caracteres',
      'passwordUpper': 'Le mot de passe doit contenir au moins 1 majuscule',
      'passwordLower': 'Le mot de passe doit contenir au moins 1 minuscule',
      'passwordNumber': 'Le mot de passe doit contenir au moins 1 chiffre',
      'passwordSpecial': 'Le mot de passe doit contenir au moins 1 caractere special',
      'confirmPasswordRequired': 'Veuillez confirmer le mot de passe',
      'passwordMismatch': 'Les mots de passe ne correspondent pas',
      'nameRequired': 'Le nom est obligatoire',
      'nameMin': 'Le nom doit avoir au moins 2 caracteres',
      'nameMax': 'Le nom doit avoir au maximum 255 caracteres',
      'usernameRequired': 'Le nom utilisateur est obligatoire',
      'usernameMax': 'Le nom utilisateur doit avoir au maximum 50 caracteres',
      'usernameFormat': 'Le nom utilisateur ne peut contenir que lettres, numeros, point et underscore',
      'bioMaxChars': 'La biographie doit avoir au maximum 5000 caracteres',
      'bioMaxWords': 'La biographie ne peut pas depasser 500 mots',
      'bioInappropriate': 'La biographie contient un langage inapproprie',
      'birthdateRequired': 'La date de naissance est obligatoire',
      'birthdateInvalid': 'Date de naissance invalide',
      'mustBe16': 'Vous devez avoir au moins 16 ans'
    }
  };
}
