/*==============================================================*/
/* dbms name:      PostgreSQL 18                               */
/* Created ON:     24/03/2026 23:18:08                          */
/*==============================================================*/

/* DROP TABLE CASCADE automatically removes all indexes, FKs,  */
/* and dependent constraints — no separate DROP INDEX needed.   */
DROP TABLE IF EXISTS administrators CASCADE;
DROP TABLE IF EXISTS announc_roles CASCADE;
DROP TABLE IF EXISTS announc_sl CASCADE;
DROP TABLE IF EXISTS application_validation_logs CASCADE;
DROP TABLE IF EXISTS areas CASCADE;
DROP TABLE IF EXISTS awarded_badges CASCADE;
DROP TABLE IF EXISTS badge_applications CASCADE;
DROP TABLE IF EXISTS badge_requirements CASCADE;
DROP TABLE IF EXISTS badge_skills CASCADE;
DROP TABLE IF EXISTS badges CASCADE;
DROP TABLE IF EXISTS certificates CASCADE;
DROP TABLE IF EXISTS consultant_areas CASCADE;
DROP TABLE IF EXISTS consultants CASCADE;
DROP TABLE IF EXISTS consultants_selected_skills CASCADE;
DROP TABLE IF EXISTS device_tokens CASCADE;
DROP TABLE IF EXISTS gdpr_consent_history CASCADE;
DROP TABLE IF EXISTS gdpr_policies CASCADE;
DROP TABLE IF EXISTS goals CASCADE;
DROP TABLE IF EXISTS integration_webhooks CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS learning_paths CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS notification_definitions CASCADE;
DROP TABLE IF EXISTS notification_preferences CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS points_history CASCADE;
DROP TABLE IF EXISTS progression_stages CASCADE;
DROP TABLE IF EXISTS requirements_evidences CASCADE;
DROP TABLE IF EXISTS rewards CASCADE;
DROP TABLE IF EXISTS service_line_leaders CASCADE;
DROP TABLE IF EXISTS service_lines CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS sl_slas CASCADE;
DROP TABLE IF EXISTS sla_breach_alerts CASCADE;
DROP TABLE IF EXISTS slas CASCADE;
DROP TABLE IF EXISTS stage_codes CASCADE;
DROP TABLE IF EXISTS system_announcements CASCADE;
DROP TABLE IF EXISTS talent_managers CASCADE;
DROP TABLE IF EXISTS user_account_tokens CASCADE;
DROP TABLE IF EXISTS user_badges_interactions CASCADE;
DROP TABLE IF EXISTS user_notification_preferences CASCADE;
DROP TABLE IF EXISTS user_refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;

/*==============================================================*/
/* EXTENSION: For indexes                                       */
/*==============================================================*/
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

/*==============================================================*/
/* TABLE: areas                                                 */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS areas (
   area_id              INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   service_line_id      INTEGER                 NOT NULL, -- FK -> service_lines(service_line_id)
   area_name            VARCHAR(100)         NOT NULL,
   area_slug            VARCHAR(512)         NOT NULL,
      CONSTRAINT uk_slug_areas UNIQUE (area_slug),
   area_description     TEXT                 NULL,
   img_url              VARCHAR(512)         NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_areas PRIMARY KEY (area_id)
);

/*==============================================================*/
/* INDEX: AREAS_PK                                              */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS AREAS_PK ON areas (area_id);

/*==============================================================*/
/* TABLE: learning_paths                                        */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS learning_paths (
   learning_path_id     INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   path_title           VARCHAR(150)         NOT NULL,
   path_slug            VARCHAR(512)         NOT NULL,
      CONSTRAINT uk_slug_lp UNIQUE (path_slug),
   path_description     TEXT                 NULL,
   img_url              VARCHAR(512)         NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,
   
   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_learning_paths PRIMARY KEY (learning_path_id)
);

/*==============================================================*/
/* INDEX: LEARNING_PATHS_PK                                     */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS LEARNING_PATHS_PK ON learning_paths (learning_path_id);

/*==============================================================*/
/* TABLE: service_lines                                        */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS service_lines (
   service_line_id      INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   learning_path_id     INTEGER                 NOT NULL, -- FK -> learning_paths(learning_path_id)
   service_line_name    VARCHAR(100)         NOT NULL,
   sl_slug              VARCHAR(512)         NOT NULL,
      CONSTRAINT uk_slug_service_lines UNIQUE (sl_slug),
   service_line_description TEXT                 NULL,
   img_url              VARCHAR(512)         NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_service_lines PRIMARY KEY (service_line_id)
);

/*==============================================================*/
/* INDEX: SERVICE_LINES_PK                                     */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SERVICE_LINES_PK ON service_lines (service_line_id);


/*==============================================================*/
/* TABLE: stage_codes                                           */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS stage_codes (
   stage_code_id        INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   stage_code           VARCHAR(20)          NOT NULL,
      CONSTRAINT uk_code_stage_co UNIQUE (stage_code),

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_stage_codes PRIMARY KEY (stage_code_id)
);

/*==============================================================*/
/* INDEX: STAGE_CODES_PK                                        */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS STAGE_CODES_PK ON stage_codes (stage_code_id);

/*==============================================================*/
/* TABLE: progression_stages                                    */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS progression_stages (
   progression_stage_id INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   area_id              INTEGER                 NOT NULL, -- FK -> areas(area_id)
   stage_code_id        INTEGER                 NOT NULL, -- FK -> stage_codes(stage_code_id)
   stage_title          VARCHAR(100)         NOT NULL,
   stage_sequence       INTEGER                 NULL,
   stage_description    TEXT                 NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_progression_stages PRIMARY KEY (progression_stage_id)
);

/*==============================================================*/
/* INDEX: PROGRESSION_STAGES_PK                                 */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS PROGRESSION_STAGES_PK ON progression_stages (progression_stage_id);

/*==============================================================*/
/* TABLE: awarded_badges                                        */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS awarded_badges (
   awarded_badges_id    INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   application_id       INTEGER                 NOT NULL, -- FK -> badge_applications(application_id)
      CONSTRAINT uk_awarded_application UNIQUE (application_id),
   user_id              INTEGER                 NULL, -- FK -> consultants(user_id)
   awarded_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   expiration_at        TIMESTAMPTZ          NULL,
   points_snapshot      INTEGER                 NULL,
   public_verification_link VARCHAR(512)         NULL,
      CONSTRAINT uk_verification_link UNIQUE (public_verification_link),
   is_published         BOOLEAN                 NOT NULL DEFAULT FALSE,
   is_featured          BOOLEAN                 NOT NULL DEFAULT FALSE,
   display_order        INTEGER                 NULL,
   last_expiry_alert_days INTEGER               NULL,

   CONSTRAINT pk_awarded_badges PRIMARY KEY (awarded_badges_id)
);

/*==============================================================*/
/* INDEX: AWARDED_BADGES_PK                                     */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS AWARDED_BADGES_PK ON awarded_badges (awarded_badges_id);

/*==============================================================*/
/* TABLE: badges                                                */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS badges (
   badge_id             INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   progression_stage_id INTEGER                 NOT NULL, -- FK -> progression_stages(progression_stage_id)
      CONSTRAINT uk_badges_stage UNIQUE (progression_stage_id),
   area_id              INTEGER                 NOT NULL, -- FK -> areas(area_id)
   service_line_id      INTEGER                 NOT NULL, -- FK -> service_lines(service_line_id)
   learning_path_id      INTEGER                 NOT NULL, -- FK -> learning_path(learning_path_id)
   badge_title          VARCHAR(100)         NOT NULL,
   badge_slug           VARCHAR(512)         NOT NULL,
      CONSTRAINT uk_slug_badges UNIQUE (badge_slug),
   badge_type           VARCHAR(128)         NOT NULL
      CONSTRAINT ckc_badge_type_badges CHECK (badge_type IN ('Standard', 'Special')),
   badge_points         INTEGER                 NOT NULL DEFAULT 0,
      CONSTRAINT ckc_positive_points CHECK (badge_points >= 0),
   expiration_duration_days INTEGER                 NULL,
   badge_description    TEXT                 NULL,
   badge_img_url        VARCHAR(512)         NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_badges PRIMARY KEY (badge_id)
);

/*==============================================================*/
/* INDEX: BADGES_PK                                             */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS BADGES_PK ON badges (badge_id);

/*==============================================================*/
/* TABLE: badge_applications                                    */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS badge_applications (
   application_id       INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   badge_id             INTEGER                 NOT NULL, -- FK -> badges(badge_id)
   user_id              INTEGER                 NOT NULL, -- FK -> consultants(user_id)
   application_guid     UUID                 NOT NULL DEFAULT gen_random_uuid(),
      CONSTRAINT uk_guid_badge_applications UNIQUE (application_guid),
   application_state    VARCHAR(30)          NOT NULL DEFAULT 'Open'
      CONSTRAINT ckc_application_state_badge_ap CHECK (application_state IN ('Open', 'Submitted', 'In validation', 'Accepted', 'Rejected')),
   consultant_notes     TEXT                 NULL,

   opened_at            TIMESTAMPTZ          NOT NULL DEFAULT now(),
   submitted_at         TIMESTAMPTZ          NULL,
   closed_at            TIMESTAMPTZ          NULL,

   CONSTRAINT pk_badge_applications PRIMARY KEY (application_id),
   CONSTRAINT ckc_date_flow CHECK ((submitted_at IS NULL OR submitted_at >= opened_at) AND (closed_at IS NULL OR (submitted_at IS NOT NULL AND closed_at >= submitted_at)))
);

/*==============================================================*/
/* INDEX: BADGE_APPLICATIONS_PK                                 */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS BADGE_APPLICATIONS_PK ON badge_applications (application_id);

/*==============================================================*/
/* TABLE: application_validation_logs                           */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS application_validation_logs (
   validation_log_id    INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   application_id       INTEGER                 NOT NULL, -- FK -> badge_applications(application_id)
   user_id              INTEGER                 NULL, -- FK -> users(user_id)
   validator_function   VARCHAR(50)          NOT NULL,
   validator_action     VARCHAR(50)          NOT NULL,
   validations_comments TEXT                 NULL,
   validated_at         TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_application_validation_logs PRIMARY KEY (validation_log_id)
);

/*==============================================================*/
/* INDEX: APPLICATION_VALIDATION_LOGS_PK                        */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS APPLICATION_VALIDATION_LOGS_PK ON application_validation_logs (validation_log_id);


/*==============================================================*/
/* TABLE: badge_requirements                                    */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS badge_requirements (
   requirement_id       INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   badge_id             INTEGER                 NOT NULL, -- FK -> badges(badge_id)
   progression_stage_id INTEGER                 NOT NULL, -- FK -> progression_stages(progression_stage_id)
   requirement_title    VARCHAR(150)         NOT NULL,
   requirement_sequence INTEGER                 NULL,
   requirement_description TEXT                 NOT NULL,
   badge_points         INTEGER                 NOT NULL DEFAULT 0,
      CONSTRAINT ckc_positive_points CHECK (badge_points >= 0),
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_badge_requirements PRIMARY KEY (requirement_id)
);

/*==============================================================*/
/* INDEX: BADGE_REQUIREMENTS_PK                                 */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS BADGE_REQUIREMENTS_PK ON badge_requirements (requirement_id);


/*==============================================================*/
/* TABLE: certificates                                          */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS certificates (
   certificate_id       INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   application_id       INTEGER                 NOT NULL, -- FK -> badge_applications(application_id)
   certificate_title    VARCHAR(150)         NOT NULL,
   issuing_entity       VARCHAR(150)         NULL,
   issue_date           DATE                 NULL,
   certificate_file_url VARCHAR(500)         NULL,
   language_code        VARCHAR(5)           NULL,

   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_certificates PRIMARY KEY (certificate_id),
   CONSTRAINT uk_certificate_application UNIQUE (application_id)
);

/*==============================================================*/
/* INDEX: CERTIFICATES_PK                                       */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS CERTIFICATES_PK ON certificates (certificate_id);

/*==============================================================*/
/* TABLE: gdpr_policies                                         */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS gdpr_policies (
   policy_id            INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   policy_type          VARCHAR(50)          NOT NULL
      CONSTRAINT ckc_policy_type_gdpr CHECK (policy_type IN ('Privacy', 'Terms', 'Cookies')),
   version              VARCHAR(30)          NOT NULL,
   policy_text          TEXT                 NULL,
   is_mandatory         BOOLEAN              NOT NULL DEFAULT TRUE,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_gdpr_policies PRIMARY KEY (policy_id),
   CONSTRAINT uq_gdpr_policy_type_version UNIQUE (policy_type, version)
);

/*==============================================================*/
/* INDEX: GDPR_POLICIES_PK                                      */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS GDPR_POLICIES_PK ON gdpr_policies (policy_id);

/*==============================================================*/
/* TABLE: gdpr_consent_history                                  */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS gdpr_consent_history (
   consent_id           INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NOT NULL, -- FK -> consultants(user_id)
   policy_id            INTEGER                 NOT NULL, -- FK -> gdpr_policies(policy_id)
   action               VARCHAR(20)          NOT NULL
      CONSTRAINT ckc_consent_action CHECK (action IN ('ACCEPTED', 'REVOKED')),
   ip_address           VARCHAR(45)          NULL,
   user_agent           TEXT                 NULL,
   consented_at         TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_gdpr_consent_history PRIMARY KEY (consent_id)
);

/*==============================================================*/
/* INDEX: GDPR_CONSENT_HISTORY_PK                               */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS GDPR_CONSENT_HISTORY_PK ON gdpr_consent_history (consent_id);

/*==============================================================*/
/* TABLE: goals                                                 */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS goals (
   goal_id              INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NULL, -- FK -> consultants(user_id)
   badge_id             INTEGER                 NULL, -- FK -> badges(badge_id)
   application_id       INTEGER                 NULL, -- FK -> badge_applications(application_id)
   event_title          VARCHAR(150)         NOT NULL,
   event_description    TEXT                 NULL,
   event_start_date     TIMESTAMPTZ          NULL,
   event_end_date       TIMESTAMPTZ          NULL,
   reminder_at          TIMESTAMPTZ          NULL,
   reminder_sent        BOOLEAN              NOT NULL DEFAULT FALSE,
   auto_reminder_sent   BOOLEAN              NOT NULL DEFAULT FALSE,

   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_goals PRIMARY KEY (goal_id)
);

/*==============================================================*/
/* INDEX: GOALS_PK                                              */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS GOALS_PK ON goals (goal_id);

/*==============================================================*/
/* TABLE: integration_webhooks                                  */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS integration_webhooks (
   webhook_id           INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   platform             VARCHAR(20)          NOT NULL
      CONSTRAINT ckc_webhook_platform CHECK (platform IN ('teams', 'slack')),
   webhook_url          TEXT                 NOT NULL,
   channel_name         VARCHAR(100)         NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_integration_webhooks PRIMARY KEY (webhook_id)
);

/*==============================================================*/
/* INDEX: INTEGRATION_WEBHOOKS_PK                               */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS INTEGRATION_WEBHOOKS_PK ON integration_webhooks (webhook_id);

/*==============================================================*/
/* TABLE: locations                                             */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS locations (
   location_id          INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   location_name        VARCHAR(128)         NOT NULL,
   
   CONSTRAINT pk_locations PRIMARY KEY (location_id)
);

/*==============================================================*/
/* INDEX: LOCATIONS_PK                                          */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS LOCATIONS_PK ON locations (location_id);

/*==============================================================*/
/* INSERT STATIC VALUES                                         */
/*==============================================================*/
-- INSERT INTO locations (location_name) 
-- VALUES 
--    ('Lisboa'), 
--    ('Tomar'), 
--    ('Viseu'), 
--    ('Fundao'), 
--    ('Portalegre'),
--    ('Remote')
-- ON CONFLICT DO NOTHING;

/*==============================================================*/
/* TABLE: notifications                                         */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS notifications (
   notification_id      INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   definition_id        INTEGER                 NOT NULL, -- FK -> notification_definitions(definition_id)
   notification_payload TEXT                 NULL,
   notification_url     VARCHAR(512)         NULL,
   notification_type    VARCHAR(50)          NOT NULL
      CONSTRAINT ckc_notification_type CHECK (notification_type IN ('HOME', 'BADGES', 'APPLICATIONS', 'ACHIEVEMENTS', 'POINTS', 'OBJECTIVES', 'EVOLUTION', 'ANNOUNCEMENTS', 'SYSTEM')),
   is_read              BOOLEAN              NOT NULL DEFAULT FALSE,
   sent_at              TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_notifications PRIMARY KEY (notification_id)
);

/*==============================================================*/
/* INDEX: NOTIFICATIONS_PK                                      */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS NOTIFICATIONS_PK ON notifications (notification_id);

/*==============================================================*/
/* TABLE: notification_definitions                              */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS notification_definitions (
   definition_id        INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   code                 VARCHAR(128)         NOT NULL,
   name                 VARCHAR(256)         NOT NULL,
   description          TEXT                 NULL,
   target_route         VARCHAR(256)         NULL,
   user_id              INTEGER                 NULL, -- FK -> administrators(user_id)

   CONSTRAINT pk_notification_definitions PRIMARY KEY (definition_id)
);

/*==============================================================*/
/* INDEX: NOTIFICATION_DEFINITIONS_PK                           */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS NOTIFICATION_DEFINITIONS_PK ON notification_definitions (definition_id);

/*==============================================================*/
/* TABLE: notification_preferences                              */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS notification_preferences (
   preference_id        INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   definition_id        INTEGER                 NULL, -- FK -> notification_definitions(definition_id)
   send_email           BOOLEAN                 NOT NULL,
   send_push            BOOLEAN                 NOT NULL,
   is_enabled           BOOLEAN                 NOT NULL,
   trigger_before_value INTEGER                 NULL,
   trigger_before_unit  VARCHAR(50)          NULL,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_notification_preferences PRIMARY KEY (preference_id)
);

/*==============================================================*/
/* INDEX: NOTIFICATE_TO_PK                                      */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS NOTIFICATE_TO_PK ON notification_preferences (preference_id);

/*==============================================================*/
/* TABLE: device_tokens                                         */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS device_tokens (
   device_token_id      INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   fcm_token            TEXT                    NOT NULL,
   device_name          VARCHAR(128)            NULL,
   platform             VARCHAR(20)             NOT NULL DEFAULT 'android'
      CONSTRAINT ckc_device_platform CHECK (platform IN ('android', 'ios')),
   is_active            BOOLEAN                 NOT NULL DEFAULT TRUE,
   created_at           TIMESTAMPTZ             NOT NULL DEFAULT now(),
   last_used_at         TIMESTAMPTZ             NOT NULL DEFAULT now(),

   CONSTRAINT pk_device_tokens PRIMARY KEY (device_token_id)
);

/*==============================================================*/
/* INDEX: DEVICE_TOKENS_PK                                      */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS DEVICE_TOKENS_PK ON device_tokens (device_token_id);

/*==============================================================*/
/* TABLE: user_notification_preferences                         */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS user_notification_preferences (
   user_pref_id         INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   definition_id        INTEGER                 NOT NULL, -- FK -> notification_definitions(definition_id)
   send_push            BOOLEAN                 NULL,
   send_email           BOOLEAN                 NULL,
   is_enabled           BOOLEAN                 NULL,
   updated_at           TIMESTAMPTZ             NOT NULL DEFAULT now(),

   CONSTRAINT pk_user_notification_preferences PRIMARY KEY (user_pref_id),
   CONSTRAINT uq_user_def UNIQUE (user_id, definition_id)
);

/*==============================================================*/
/* INDEX: USER_NOTIFICATION_PREFERENCES_PK                      */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS USER_NOTIFICATION_PREFERENCES_PK ON user_notification_preferences (user_pref_id);

/*==============================================================*/
/* TABLE: sla_breach_alerts                                     */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS sla_breach_alerts (
   alert_id             INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   sla_id               INTEGER                 NOT NULL, -- FK -> slas(sla_id)
   application_id       INTEGER                 NULL, -- FK -> badge_applications(application_id), NULL for standalone SLAs
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id), the alerted recipient
   alerted_at           TIMESTAMPTZ             NOT NULL DEFAULT now(),

   CONSTRAINT pk_sla_breach_alerts PRIMARY KEY (alert_id)
);

/*==============================================================*/
/* INDEX: SLA_BREACH_ALERTS_PK                                  */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SLA_BREACH_ALERTS_PK ON sla_breach_alerts (alert_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sla_breach_unique ON sla_breach_alerts (sla_id, COALESCE(application_id, 0), user_id);

/*==============================================================*/
/* TABLE: points_history                                        */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS points_history (
   points_history_id    INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NOT NULL, -- FK -> consultants(user_id)
   requirement_id       INTEGER                 NULL, -- FK -> badge_requirements(requirement_id)
   badge_id             INTEGER                 NULL, -- FK -> badges(badge_id)
   points_delta         INTEGER                 NOT NULL,
   justification        TEXT                 NULL,
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_points_history PRIMARY KEY (points_history_id)
);

/*==============================================================*/
/* INDEX: POINTS_HISTORY_PK                                     */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS POINTS_HISTORY_PK ON points_history (points_history_id);

/*==============================================================*/
/* TABLE: languages                                             */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS languages (
   language_id    INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   language_iso       VARCHAR(20)          NOT NULL,
      CONSTRAINT uk_lang_preferred UNIQUE (language_iso),
      CONSTRAINT ckc_languages_supported CHECK (language_iso IN ('pt-PT', 'en-GB', 'es-ES')),
   language_name     VARCHAR(128)      NOT NULL,

   CONSTRAINT pk_languages PRIMARY KEY (language_id)
);

/*==============================================================*/
/* INDEX: LANGUAGES_PK                                          */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS LANGUAGES_PK ON languages (language_id);

/*==============================================================*/
/* INSERT STATIC VALUES                                         */
/*==============================================================*/
-- INSERT INTO languages (language_iso, language_name) 
-- VALUES 
--    ('pt-PT', 'Portuguese (Portugal)'),
--    ('en-GB', 'English (United Kingdom)'),
--    ('es-ES', 'Spanish (Spain)')
-- ON CONFLICT (language_iso) DO NOTHING;

/*==============================================================*/
/* TABLE: requirements_evidences                                */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS requirements_evidences (
   evidence_id          INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   application_id       INTEGER                 NOT NULL, -- FK -> badge_applications(application_id)
   requirement_id       INTEGER                 NULL, -- FK -> badge_requirements(requirement_id)
   evidence_file_url    VARCHAR(500)         NOT NULL,
   evidence_title       VARCHAR(150)         NULL,
   evidence_description TEXT                 NULL,
   evidence_file_type   VARCHAR(100)         NULL,
   tm_reviewed          BOOLEAN              NOT NULL DEFAULT FALSE,
   sll_reviewed         BOOLEAN              NOT NULL DEFAULT FALSE,
   uploaded_at          TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_requirements_evidences PRIMARY KEY (evidence_id),
   CONSTRAINT uk_one_evidence_per_req UNIQUE (application_id, requirement_id)
);

/*==============================================================*/
/* INDEX: REQUIREMENTS_EVIDENCES_PK                             */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS REQUIREMENTS_EVIDENCES_PK ON requirements_evidences (evidence_id);

/*==============================================================*/
/* TABLE: rewards                                               */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS rewards (
   reward_id            INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   reward_guid          UUID                 NOT NULL DEFAULT gen_random_uuid(),
   badge_id             INTEGER                 NULL, -- FK -> badges(badge_id)
   special_title        VARCHAR(255)         NULL,
   special_portrait_svg TEXT                 NULL,
   -- Points store: a redeemable course/perk with a (static) access link.
   reward_name          VARCHAR(150)         NULL,
   reward_description   TEXT                 NULL,
   access_link          TEXT                 NULL,
   access_info          TEXT                 NULL, -- static credentials/notes emailed on redemption
   cost_points          INTEGER              NOT NULL DEFAULT 0,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   CONSTRAINT pk_rewards PRIMARY KEY (reward_id)
);

/*==============================================================*/
/* TABLE: reward_redemptions                                    */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS reward_redemptions (
   redemption_id        INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   redemption_guid      UUID                 NOT NULL DEFAULT gen_random_uuid(),
   reward_id            INTEGER              NOT NULL, -- FK -> rewards(reward_id)
   user_id              INTEGER              NOT NULL, -- FK -> users(user_id)
   points_spent         INTEGER              NOT NULL,
   redeemed_at          TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_reward_redemptions PRIMARY KEY (redemption_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS REWARD_REDEMPTIONS_PK ON reward_redemptions (redemption_id);
CREATE INDEX IF NOT EXISTS idx_reward_redemptions_user ON reward_redemptions (user_id);

/*==============================================================*/
/* INDEX: REWARDS_PK                                            */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS REWARDS_PK ON rewards (reward_id);

/*==============================================================*/
/* TABLE: skills                                                */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS skills (
   skills_id            INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   skill_name           VARCHAR(150)         NOT NULL,
   skill_description    TEXT                 NULL,

   created_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   
   CONSTRAINT pk_skills PRIMARY KEY (skills_id)
);

/*==============================================================*/
/* INDEX: SKILLS_PK                                             */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SKILLS_PK ON skills (skills_id);

/*==============================================================*/
/* TABLE: slas                                                  */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS slas (
   sla_id               INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   sla_name             VARCHAR(100)         NOT NULL,
   response_time_hours  INTEGER                 NOT NULL,
      CONSTRAINT ckc_sla_response_time CHECK (response_time_hours > 0),
   start_date           TIMESTAMPTZ          NOT NULL,
   end_date             TIMESTAMPTZ          NOT NULL,
   target_profile       VARCHAR(128)         NULL
      CONSTRAINT ckc_target_profile_slas CHECK (target_profile IN ('Consultant', 'Talent Manager', 'Service Line Leader', 'Administrator')),
   is_global            BOOLEAN              NOT NULL DEFAULT FALSE,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,
   sla_description      TEXT                 NULL,
   definition_id        INTEGER                 NULL, -- FK -> notification_definitions(definition_id)
   user_id              INTEGER                 NULL, -- FK -> users(user_id)
   created_by           INTEGER                 NOT NULL, -- FK -> administrators(user_id)
   updated_by           INTEGER                 NULL, -- FK -> administrators(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_slas PRIMARY KEY (sla_id)
);

/*==============================================================*/
/* INDEX: SLA_DEFINITIONS_PK                                    */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SLA_DEFINITIONS_PK ON slas (sla_id);

/*==============================================================*/
/* TABLE: sl_slas                                               */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS sl_slas (
   service_line_id      INTEGER                 NOT NULL, -- FK -> service_lines(service_line_id)
   sla_id               INTEGER                 NOT NULL, -- FK -> slas(sla_id)

   CONSTRAINT pk_sl_slas PRIMARY KEY (service_line_id, sla_id)
);

/*==============================================================*/
/* INDEX: SL_SLAS_PK                                            */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SL_SLAS_PK ON sl_slas (service_line_id, sla_id);

/*==============================================================*/
/* TABLE: system_announcements                                  */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS system_announcements (
   announcement_id      INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   announcement_title   VARCHAR(150)         NOT NULL,
   announcement_message TEXT                 NOT NULL,
   starts_at            TIMESTAMPTZ          NULL,
   ends_at              TIMESTAMPTZ          NULL,
   announcement_type    VARCHAR(128)         NULL,
      CONSTRAINT ckc_announcement_type CHECK(announcement_type IN ('Information', 'Warning', 'New Content', 'Other')),
   is_global            BOOLEAN                 NULL,
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,

   created_by           INTEGER                 NULL, -- FK -> users(user_id)
   updated_by           INTEGER                 NULL, -- FK -> users(user_id)
   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_system_announcements PRIMARY KEY (announcement_id)
);

/*==============================================================*/
/* INDEX: SYSTEM_ANNOUNCEMENTS_PK                               */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SYSTEM_ANNOUNCEMENTS_PK ON system_announcements (announcement_id);

/*==============================================================*/
/* TABLE: announc_sl                                            */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS announc_sl (
   announcement_id      INTEGER                 NOT NULL, -- FK -> system_announcements(announcement_id)
   service_line_id      INTEGER                 NOT NULL, -- FK -> service_lines(service_line_id)

   CONSTRAINT pk_announc_sl PRIMARY KEY (announcement_id, service_line_id)
);

/*==============================================================*/
/* INDEX: ANNOUNC_SL_PK                                         */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS ANNOUNC_SL_PK ON announc_sl (announcement_id, service_line_id);

/*==============================================================*/
/* TABLE: announc_roles                                         */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS announc_roles (
   announcement_id      INTEGER                 NOT NULL, -- FK -> system_announcements(announcement_id)
   role_name            VARCHAR(50)             NOT NULL
      CONSTRAINT ckc_role_name_announc_roles CHECK (role_name IN ('Consultant', 'Talent Manager', 'Service Line Leader', 'Administrator')),

   CONSTRAINT pk_announc_roles PRIMARY KEY (announcement_id, role_name)
);

/*==============================================================*/
/* INDEX: ANNOUNC_ROLES_PK                                      */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS ANNOUNC_ROLES_PK ON announc_roles (announcement_id, role_name);

/*==============================================================*/
/* TABLE: administrators                                        */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS administrators (
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   is_super_admin       BOOLEAN                 NULL,
   location_id          INTEGER                 NULL,
   interaction_id       INTEGER                 NULL,

   CONSTRAINT pk_administrators PRIMARY KEY (user_id)
);

/*==============================================================*/
/* INDEX: ADMINISTRATORS_PK                                     */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS ADMINISTRATORS_PK ON administrators (user_id);

/*==============================================================*/
/* TABLE: consultants                                           */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS consultants (
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   gdpr_accepted        BOOLEAN                 NOT NULL DEFAULT FALSE,
   biography            TEXT                 NULL,

   CONSTRAINT pk_consultants PRIMARY KEY (user_id)
);

/*==============================================================*/
/* INDEX: CONSULTANTS_PK                                        */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS CONSULTANTS_PK ON consultants (user_id);

/*==============================================================*/
/* TABLE: consultants_selected_skills                           */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS consultants_selected_skills (
   user_id              INTEGER                 NOT NULL, -- FK -> consultants(user_id)
   skills_id            INTEGER                 NOT NULL, -- FK -> skills(skills_id)

   CONSTRAINT pk_consultants_selected_skills PRIMARY KEY (user_id, skills_id)
);

/*==============================================================*/
/* INDEX: CONSULTANTS_SELECTED_SKILLS_PK                        */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS CONSULTANTS_SELECTED_SKILLS_PK ON consultants_selected_skills (user_id, skills_id);

/*==============================================================*/
/* TABLE: badge_skills                                          */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS badge_skills (
   badge_id             INTEGER                 NOT NULL, -- FK -> badges(badge_id)
   skills_id            INTEGER                 NOT NULL, -- FK -> skills(skills_id)

   CONSTRAINT pk_badge_skills PRIMARY KEY (badge_id, skills_id)
);

/*==============================================================*/
/* INDEX: BADGE_SKILLS_PK                                       */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS BADGE_SKILLS_PK ON badge_skills (badge_id, skills_id);

/*==============================================================*/
/* TABLE: consultant_areas                                      */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS consultant_areas (
   user_id              INTEGER                 NOT NULL, -- FK -> consultants(user_id)
   area_id              INTEGER                 NOT NULL, -- FK -> areas(area_id)
   is_primary           BOOLEAN                 NOT NULL DEFAULT TRUE,

   CONSTRAINT pk_consultant_areas PRIMARY KEY (user_id, area_id)
);

/*==============================================================*/
/* INDEX: CONSULTANT_AREAS_PK                                   */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS CONSULTANT_AREAS_PK ON consultant_areas (user_id, area_id);

/*==============================================================*/
/* TABLE: service_line_leaders                                  */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS service_line_leaders (
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   service_line_id      INTEGER                 NOT NULL, -- FK -> service_lines(service_line_id)
   biography            TEXT                 NULL,

   CONSTRAINT pk_service_line_leaders PRIMARY KEY (user_id)
);

/*==============================================================*/
/* INDEX: SERVICE_LINE_LEADERS_PK                               */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS SERVICE_LINE_LEADERS_PK ON service_line_leaders (user_id);

/*==============================================================*/
/* TABLE: talent_managers                                       */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS talent_managers (
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   biography            TEXT                 NULL,

   CONSTRAINT pk_talent_managers PRIMARY KEY (user_id)
);

/*==============================================================*/
/* INDEX: TALENT_MANAGERS_PK                                    */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS TALENT_MANAGERS_PK ON talent_managers (user_id);

/*==============================================================*/
/* TABLE: users                                                 */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS users (
   user_id              INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   full_name            VARCHAR(255)         NOT NULL,
   username             VARCHAR(50)          NOT NULL,
      CONSTRAINT uk_usernam_users UNIQUE (username),
   email_address        VARCHAR(255)         NOT NULL,
      CONSTRAINT uk_email_users UNIQUE (email_address),
   password_hash        VARCHAR(255)         NOT NULL,
   user_role            VARCHAR(50)          NOT NULL DEFAULT 'Consultant',
      CONSTRAINT ckc_user_role_users CHECK (user_role IN ('Consultant', 'Talent Manager', 'Service Line Leader', 'Administrator')),
   user_guid            UUID                 NOT NULL DEFAULT gen_random_uuid(),
   phone_number         VARCHAR(20)          NULL,
   birthdate            DATE                 NULL,
   profile_img_url      VARCHAR(512)         NULL,
   language_id          INTEGER              NOT NULL DEFAULT 1, -- FK -> languages(language_id); DEFAULT is 'pt-PT' (ID=1)
   location_id          INTEGER              NULL, -- FK -> locations(location_id)
   approved_by          INTEGER              NULL, -- FK -> administrators(user_id)
   is_active            BOOLEAN              NOT NULL DEFAULT TRUE,
   email_confirmed      BOOLEAN              NOT NULL DEFAULT FALSE,
   force_password_change BOOLEAN             NOT NULL DEFAULT TRUE,
   last_login_at        TIMESTAMPTZ          NULL,
   last_online          TIMESTAMPTZ          NULL,
   current_streak_days  INTEGER              NOT NULL DEFAULT 0,

   created_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),
   updated_at           TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_users PRIMARY KEY (user_id)
);

/*==============================================================*/
/* INDEX: USERS_PK                                              */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS USERS_PK ON users (user_id);

/*==============================================================*/
/* TABLE: user_account_tokens                                   */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS user_account_tokens (
   token_id                INTEGER GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
   user_id                 INTEGER                                      NOT NULL, -- FK -> users(user_id)
   token_value             VARCHAR(512)                                 NOT NULL,

   --IS token to confirm account OR to reset password?
   token_type              VARCHAR(50)                                 NOT NULL,
      CONSTRAINT ckc_token_type_user_tokens CHECK (token_type IN ('CONFIRMATION', 'PASSWORD_RESET')),

   expires_at              TIMESTAMPTZ                                  NOT NULL,
   is_used                 BOOLEAN                                      NOT NULL DEFAULT FALSE,
   created_at              TIMESTAMPTZ                                  NOT NULL DEFAULT now(),

   CONSTRAINT pk_user_account_tokens PRIMARY KEY (token_id)
);

/*==============================================================*/
/* TABLE: user_refresh_tokens                                   */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS user_refresh_tokens (
   token_id                INTEGER GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
   user_id                 INTEGER                                      NOT NULL, -- FK -> users(user_id)
   token_value             VARCHAR(512)                                 NOT NULL,
   expires_at              TIMESTAMPTZ                                  NOT NULL,
   is_persistent           BOOLEAN                                      NOT NULL DEFAULT FALSE,
   created_at              TIMESTAMPTZ                                  NOT NULL DEFAULT now(),

   CONSTRAINT pk_user_refresh_tokens PRIMARY KEY (token_id)
);

/*==============================================================*/
/* TABLE: user_badges_interactions                              */
/*==============================================================*/
CREATE TABLE IF NOT EXISTS user_badges_interactions (
   interaction_id       INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
   user_id              INTEGER                 NOT NULL, -- FK -> users(user_id)
   badge_id             INTEGER                 NOT NULL, -- FK -> badges(badge_id)
   interaction_type     VARCHAR(50)         NOT NULL,
      CONSTRAINT ckc_interaction_type CHECK (interaction_type IN ('VIEW', 'SHARE_LINKEDIN', 'FAVORITE')),
   interaction_date     TIMESTAMPTZ          NOT NULL DEFAULT now(),

   CONSTRAINT pk_user_badges_interactions PRIMARY KEY (interaction_id)
);

/*==============================================================*/
/* INDEX: USER_BADGES_INTERACTIONS_PK                           */
/*==============================================================*/
CREATE UNIQUE INDEX IF NOT EXISTS USER_BADGES_INTERACTIONS_PK ON user_badges_interactions (interaction_id);

ALTER TABLE administrators
   ADD CONSTRAINT fk_administ_users_inh_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE announc_sl
   ADD CONSTRAINT fk_announc__announc_s_system_a FOREIGN KEY (announcement_id)
      REFERENCES system_announcements (announcement_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE announc_sl
   ADD CONSTRAINT fk_announc__announc_s_services FOREIGN KEY (service_line_id)
      REFERENCES service_lines (service_line_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE announc_roles
   ADD CONSTRAINT fk_announc_roles_system_a FOREIGN KEY (announcement_id)
      REFERENCES system_announcements (announcement_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE application_validation_logs
   ADD CONSTRAINT fk_applicat_applicati_badge_ap FOREIGN KEY (application_id)
      REFERENCES badge_applications (application_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE application_validation_logs
   ADD CONSTRAINT fk_applicat_users_val_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE areas
   ADD CONSTRAINT fk_areas_area_crea_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE areas
   ADD CONSTRAINT fk_areas_area_upda_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE areas
   ADD CONSTRAINT fk_areas_sl_areas_services FOREIGN KEY (service_line_id)
      REFERENCES service_lines (service_line_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE awarded_badges
   ADD CONSTRAINT fk_awarded__awarded_a_badge_ap FOREIGN KEY (application_id)
      REFERENCES badge_applications (application_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE awarded_badges
   ADD CONSTRAINT fk_awarded__cons_awar_consulta FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badges
   ADD CONSTRAINT fk_badges_area_badg_areas FOREIGN KEY (area_id)
      REFERENCES areas (area_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badges
   ADD CONSTRAINT fk_badges_badges_cr_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badges
   ADD CONSTRAINT fk_badges_badges_up_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badges
   ADD CONSTRAINT fk_badges_stages_ba_progress FOREIGN KEY (progression_stage_id)
      REFERENCES progression_stages (progression_stage_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badges
   ADD CONSTRAINT fk_badges_sl_service_lines FOREIGN KEY (service_line_id)
      REFERENCES service_lines (service_line_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badges
   ADD CONSTRAINT fk_badges_lp_learning_paths FOREIGN KEY (learning_path_id)
      REFERENCES learning_paths (learning_path_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_applications
   ADD CONSTRAINT fk_badge_ap_badges_ap_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_applications
   ADD CONSTRAINT fk_badge_ap_cons_apll_consulta FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_requirements
   ADD CONSTRAINT fk_badge_re_badges_re_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_requirements
   ADD CONSTRAINT fk_badge_re_stages_re_progress FOREIGN KEY (progression_stage_id)
      REFERENCES progression_stages (progression_stage_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_requirements
   ADD CONSTRAINT fk_badge_re_require_c_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_requirements
   ADD CONSTRAINT fk_badge_re_require_u_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE certificates
   ADD CONSTRAINT fk_certific_applicati_badge_ap FOREIGN KEY (application_id)
      REFERENCES badge_applications (application_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE consultants
   ADD CONSTRAINT fk_consulta_users_inh_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE consultants_selected_skills
   ADD CONSTRAINT fk_consulta_consultan_consulta FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE consultants_selected_skills
   ADD CONSTRAINT fk_consulta_consultan_skills FOREIGN KEY (skills_id)
      REFERENCES skills (skills_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_skills
   ADD CONSTRAINT fk_badge_skills_badge_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE badge_skills
   ADD CONSTRAINT fk_badge_skills_skills_skills FOREIGN KEY (skills_id)
      REFERENCES skills (skills_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE consultant_areas
   ADD CONSTRAINT fk_cons_areas_user_consulta FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE consultant_areas
   ADD CONSTRAINT fk_consulta_consultan_areas FOREIGN KEY (area_id)
      REFERENCES areas (area_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gdpr_policies
   ADD CONSTRAINT fk_gdpr_pol_gdpr_crea_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gdpr_policies
   ADD CONSTRAINT fk_gdpr_pol_gdpr_upda_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gdpr_consent_history
   ADD CONSTRAINT fk_gdpr_consent_user FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE gdpr_consent_history
   ADD CONSTRAINT fk_gdpr_consent_policy FOREIGN KEY (policy_id)
      REFERENCES gdpr_policies (policy_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE goals
   ADD CONSTRAINT fk_goals_cons_time_consulta FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE goals
   ADD CONSTRAINT fk_goals_goals_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE goals
   ADD CONSTRAINT fk_goals_timelines_badge_ap FOREIGN KEY (application_id)
      REFERENCES badge_applications (application_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE integration_webhooks
   ADD CONSTRAINT fk_webhooks_created_by FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE integration_webhooks
   ADD CONSTRAINT fk_webhooks_updated_by FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE learning_paths
   ADD CONSTRAINT fk_learning_lp_create_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE learning_paths
   ADD CONSTRAINT fk_learning_lp_update_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE notifications
   ADD CONSTRAINT fk_notifica_notif_def_notifica FOREIGN KEY (definition_id)
      REFERENCES notification_definitions (definition_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE notifications
   ADD CONSTRAINT fk_notifica_user_noti_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE notification_definitions
   ADD CONSTRAINT fk_notifica_admin_def_administ FOREIGN KEY (user_id)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE notification_preferences
   ADD CONSTRAINT fk_notifica_notificat_notifica FOREIGN KEY (definition_id)
      REFERENCES notification_definitions (definition_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE notification_preferences
   ADD CONSTRAINT fk_notifica_notpref_c_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE notification_preferences
   ADD CONSTRAINT fk_notifica_notpref_u_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE device_tokens
   ADD CONSTRAINT fk_device_t_user_devi_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE user_notification_preferences
   ADD CONSTRAINT fk_user_not_user_pref_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE user_notification_preferences
   ADD CONSTRAINT fk_user_not_def_pref_notif_def FOREIGN KEY (definition_id)
      REFERENCES notification_definitions (definition_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE sla_breach_alerts
   ADD CONSTRAINT fk_sla_breach_sla FOREIGN KEY (sla_id)
      REFERENCES slas (sla_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE sla_breach_alerts
   ADD CONSTRAINT fk_sla_breach_app FOREIGN KEY (application_id)
      REFERENCES badge_applications (application_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE sla_breach_alerts
   ADD CONSTRAINT fk_sla_breach_user FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE points_history
   ADD CONSTRAINT fk_points_h_badges_po_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE points_history
   ADD CONSTRAINT fk_points_h_cons_poin_consulta FOREIGN KEY (user_id)
      REFERENCES consultants (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE points_history
   ADD CONSTRAINT fk_points_h_requireme_badge_re FOREIGN KEY (requirement_id)
      REFERENCES badge_requirements (requirement_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE progression_stages
   ADD CONSTRAINT fk_progress_areas_sta_areas FOREIGN KEY (area_id)
      REFERENCES areas (area_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE progression_stages
   ADD CONSTRAINT fk_progress_stages_cr_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE progression_stages
   ADD CONSTRAINT fk_progress_stages_up_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE progression_stages
   ADD CONSTRAINT fk_progress_stage_sta_stage_co FOREIGN KEY (stage_code_id)
      REFERENCES stage_codes (stage_code_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE requirements_evidences
   ADD CONSTRAINT fk_requirem_applicati_badge_ap FOREIGN KEY (application_id)
      REFERENCES badge_applications (application_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE requirements_evidences
   ADD CONSTRAINT fk_requirem_requireme_badge_re FOREIGN KEY (requirement_id)
      REFERENCES badge_requirements (requirement_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE rewards
   ADD CONSTRAINT fk_rewards_badge_rew_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE reward_redemptions
   ADD CONSTRAINT fk_redemptions_reward FOREIGN KEY (reward_id)
      REFERENCES rewards (reward_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE reward_redemptions
   ADD CONSTRAINT fk_redemptions_user FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE service_lines
   ADD CONSTRAINT fk_services_sl_create_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE service_lines
   ADD CONSTRAINT fk_services_sl_lp_learning FOREIGN KEY (learning_path_id)
      REFERENCES learning_paths (learning_path_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE service_lines
   ADD CONSTRAINT fk_services_sl_update_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE service_line_leaders
   ADD CONSTRAINT fk_service__sl_sll_services FOREIGN KEY (service_line_id)
      REFERENCES service_lines (service_line_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE service_line_leaders
   ADD CONSTRAINT fk_service__users_inh_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE skills
   ADD CONSTRAINT fk_skills_skills_cr_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE skills
   ADD CONSTRAINT fk_skills_skills_up_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE slas
   ADD CONSTRAINT fk_slas_notificat_notifica FOREIGN KEY (definition_id)
      REFERENCES notification_definitions (definition_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE slas
   ADD CONSTRAINT fk_slas_slas_crea_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE slas
   ADD CONSTRAINT fk_slas_slas_upda_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE slas
   ADD CONSTRAINT fk_slas_user_slas_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE sl_slas
   ADD CONSTRAINT fk_sl_slas_sl_slas_services FOREIGN KEY (service_line_id)
      REFERENCES service_lines (service_line_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE sl_slas
   ADD CONSTRAINT fk_sl_slas_sl_slas2_slas FOREIGN KEY (sla_id)
      REFERENCES slas (sla_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE stage_codes
   ADD CONSTRAINT fk_stage_co_stagecode_administ FOREIGN KEY (created_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE stage_codes
   ADD CONSTRAINT fk_stage_co_stage_cod_administ FOREIGN KEY (updated_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE system_announcements
   ADD CONSTRAINT fk_system_a_announcem_users FOREIGN KEY (created_by)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE system_announcements
   ADD CONSTRAINT fk_system_a_announc_u_users FOREIGN KEY (updated_by)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE talent_managers
   ADD CONSTRAINT fk_talent_m_users_inh_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE users
   ADD CONSTRAINT fk_users_lang_user_languages FOREIGN KEY (language_id)
      REFERENCES languages (language_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE users
   ADD CONSTRAINT fk_users_location__location FOREIGN KEY (location_id)
      REFERENCES locations (location_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE users
   ADD CONSTRAINT fk_users_approved_by_administ FOREIGN KEY (approved_by)
      REFERENCES administrators (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE user_badges_interactions
   ADD CONSTRAINT fk_user_bad_badges_in_badges FOREIGN KEY (badge_id)
      REFERENCES badges (badge_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE user_badges_interactions
   ADD CONSTRAINT fk_user_bad_user_inte_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE user_account_tokens  
   ADD CONSTRAINT fk_user_tokens_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE user_refresh_tokens
   ADD CONSTRAINT fk_refresh_users FOREIGN KEY (user_id)
      REFERENCES users (user_id)
      ON DELETE CASCADE;

/*==============================================================*/
/* FK SUPPORTING INDEXES (CREATED AFTER FK CONSTRAINTS)         */
/*==============================================================*/
CREATE INDEX IF NOT EXISTS SL_AREAS_FK ON areas (service_line_id);
CREATE INDEX IF NOT EXISTS AREA_CREATEDBY_FK ON areas (created_by);
CREATE INDEX IF NOT EXISTS AREA_UPDATEDBY_FK ON areas (updated_by);
CREATE INDEX IF NOT EXISTS ADMIN_LP_FK ON learning_paths (created_by);
CREATE INDEX IF NOT EXISTS LP_UPDATEDBY_FK ON learning_paths (updated_by);
CREATE INDEX IF NOT EXISTS SL_LP_FK ON service_lines (learning_path_id);
CREATE INDEX IF NOT EXISTS ADMIN_SL_FK ON service_lines (created_by);
CREATE INDEX IF NOT EXISTS SL_UPDATEDBY_FK ON service_lines (updated_by);
CREATE INDEX IF NOT EXISTS STAGE_CODE_CREATEDBY_FK ON stage_codes (created_by);
CREATE INDEX IF NOT EXISTS STAGE_CODE_UPDATEDBY_FK ON stage_codes (updated_by);
CREATE INDEX IF NOT EXISTS AREAS_STAGES_FK ON progression_stages (area_id);
CREATE INDEX IF NOT EXISTS STAGE_STAGECODES_FK ON progression_stages (stage_code_id);
CREATE INDEX IF NOT EXISTS STAGES_CREATEDBY_FK ON progression_stages (created_by);
CREATE INDEX IF NOT EXISTS STAGES_UPDATEDBY_FK ON progression_stages (updated_by);
CREATE INDEX IF NOT EXISTS CONS_AWARDED_FK ON awarded_badges (user_id);
CREATE INDEX IF NOT EXISTS AWARDED_APPLICATIONS2_FK ON awarded_badges (application_id);
CREATE INDEX IF NOT EXISTS STAGES_BADGES2_FK ON badges (progression_stage_id);
CREATE INDEX IF NOT EXISTS AREA_BADGES_FK ON badges (area_id);
CREATE INDEX IF NOT EXISTS BADGES_CREATEDBY_FK ON badges (created_by);
CREATE INDEX IF NOT EXISTS BADGES_UPDATEDBY_FK ON badges (updated_by);
CREATE INDEX IF NOT EXISTS SL_BADGES_FK ON badges (service_line_id);
CREATE INDEX IF NOT EXISTS LP_BADGES_FK ON badges (learning_path_id);
CREATE INDEX IF NOT EXISTS BADGES_APPLICATIONS_FK ON badge_applications (badge_id);
CREATE INDEX IF NOT EXISTS CONS_APLLICATIONS_FK ON badge_applications (user_id);
CREATE INDEX IF NOT EXISTS APPLICATIONS_VALIDATIONS_FK ON application_validation_logs (application_id);
CREATE INDEX IF NOT EXISTS USERS_VALIDATIONS_FK ON application_validation_logs (user_id);
CREATE INDEX IF NOT EXISTS STAGES_REQUIREMENTS_FK ON badge_requirements (progression_stage_id);
CREATE INDEX IF NOT EXISTS BADGES_REQUIREMENTS_FK ON badge_requirements (badge_id);
CREATE INDEX IF NOT EXISTS REQUIREMENTS_CREATEDBY_FK ON badge_requirements (created_by);
CREATE INDEX IF NOT EXISTS REQUIREMENTS_UPDATEDBY_FK ON badge_requirements (updated_by);
CREATE INDEX IF NOT EXISTS APPLICATIONS_CERTIFICATES2_FK ON certificates (application_id);
CREATE INDEX IF NOT EXISTS GDPR_UPDATEDBY_FK ON gdpr_policies (updated_by);
CREATE INDEX IF NOT EXISTS GDPR_CREATEDBY_FK ON gdpr_policies (created_by);
CREATE INDEX IF NOT EXISTS IDX_GDPR_CONSENT_USER ON gdpr_consent_history (user_id);
CREATE INDEX IF NOT EXISTS IDX_GDPR_CONSENT_POLICY ON gdpr_consent_history (policy_id);
CREATE INDEX IF NOT EXISTS IDX_GDPR_CONSENT_DATE ON gdpr_consent_history (consented_at DESC);
CREATE INDEX IF NOT EXISTS CONS_TIMELINES_FK ON goals (user_id);
CREATE INDEX IF NOT EXISTS TIMELINES_APPLICATIONS_FK ON goals (application_id);
CREATE INDEX IF NOT EXISTS GOALS_FK ON goals (badge_id);
CREATE INDEX IF NOT EXISTS IDX_WEBHOOKS_ACTIVE ON integration_webhooks (is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS WEBHOOKS_UPDATEDBY_FK ON integration_webhooks (updated_by);
CREATE INDEX IF NOT EXISTS USER_NOTIFICATIONS_FK ON notifications (user_id);
CREATE INDEX IF NOT EXISTS NOTIF_DEF_FK ON notifications (definition_id);
CREATE INDEX IF NOT EXISTS ADMIN_DEF_FK ON notification_definitions (user_id);
CREATE INDEX IF NOT EXISTS NOT_DEF_PREF2_FK ON notification_preferences (definition_id);
CREATE INDEX IF NOT EXISTS NOT_PREFERENCES_CREATEDBY_FK ON notification_preferences (created_by);
CREATE INDEX IF NOT EXISTS NOT_PREFERENCES_UPDATEDBY_FK ON notification_preferences (updated_by);
CREATE INDEX IF NOT EXISTS CONS_POINTS_FK ON points_history (user_id);
CREATE INDEX IF NOT EXISTS BADGES_POINTS_FK ON points_history (badge_id);
CREATE INDEX IF NOT EXISTS REQUIREMENTS_POINTS_FK ON points_history (requirement_id);
CREATE INDEX IF NOT EXISTS REQUIREMENTS_EVIDENCES_FK ON requirements_evidences (requirement_id);
CREATE INDEX IF NOT EXISTS APPLICATIONS_EVIDENCES_FK ON requirements_evidences (application_id);
CREATE INDEX IF NOT EXISTS BADGE_REWARDS_FK ON rewards (badge_id);
CREATE INDEX IF NOT EXISTS SKILLS_CREATEDBY_FK ON skills (created_by);
CREATE INDEX IF NOT EXISTS SKILLS_UPDATEDBY_FK ON skills (updated_by);
CREATE INDEX IF NOT EXISTS ADMIN_SLA_FK ON slas (created_by);
CREATE INDEX IF NOT EXISTS USER_SLAS_FK ON slas (user_id);
CREATE INDEX IF NOT EXISTS NOT_DEF_SLAS_FK ON slas (definition_id);
CREATE INDEX IF NOT EXISTS SLAS_UPDATEDBY_FK ON slas (updated_by);
CREATE INDEX IF NOT EXISTS ANNOUNCEMENTS_CREATEDBY_FK ON system_announcements (created_by);
CREATE INDEX IF NOT EXISTS ANNOUNCEMENTS_UPDATEDBY_FK ON system_announcements (updated_by);
CREATE INDEX IF NOT EXISTS SL_SLL_FK ON service_line_leaders (service_line_id);
CREATE INDEX IF NOT EXISTS LANG_USER_FK ON users (language_id);
CREATE INDEX IF NOT EXISTS LOCATION_USER_FK ON users (location_id);
CREATE INDEX IF NOT EXISTS APPROVEDBY_USER_FK ON users (approved_by);
CREATE INDEX IF NOT EXISTS USER_INTERACTIONS_FK ON user_badges_interactions (user_id);
CREATE INDEX IF NOT EXISTS BADGES_INTERACTIONS_FK ON user_badges_interactions (badge_id);

/*==============================================================*/
/* INDEXES FOR FASTER QUERYING                                  */
/*==============================================================*/
CREATE INDEX IF NOT EXISTS idx_users_role_active ON users (user_role, is_active);
CREATE INDEX IF NOT EXISTS idx_users_role_approved_by_active ON users (user_role, approved_by) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_users_full_name ON users (full_name);
CREATE INDEX IF NOT EXISTS idx_badge_apps_user_state ON badge_applications (user_id, application_state);
CREATE INDEX IF NOT EXISTS idx_badge_apps_state ON badge_applications (application_state);
CREATE INDEX IF NOT EXISTS idx_badge_apps_submitted ON badge_applications (submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_badge_apps_badge ON badge_applications (badge_id);
CREATE INDEX IF NOT EXISTS idx_badges_area_active ON badges (area_id, is_active);
CREATE INDEX IF NOT EXISTS idx_badges_points ON badges (badge_points DESC);
CREATE INDEX IF NOT EXISTS idx_badges_type ON badges (badge_type);
CREATE INDEX IF NOT EXISTS idx_awarded_user_date ON awarded_badges (user_id, awarded_at DESC);
CREATE INDEX IF NOT EXISTS idx_awarded_expiration ON awarded_badges (expiration_at) WHERE expiration_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_awarded_public_featured ON awarded_badges (is_published, is_featured);
CREATE INDEX IF NOT EXISTS idx_points_user_delta ON points_history (user_id, points_delta);
CREATE INDEX IF NOT EXISTS idx_points_history_user_created ON points_history (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_interactions_user_date ON user_badges_interactions (user_id, interaction_date DESC);
CREATE INDEX IF NOT EXISTS idx_interactions_badge_date ON user_badges_interactions (badge_id, interaction_date DESC);
CREATE INDEX IF NOT EXISTS idx_validation_logs_app ON application_validation_logs (application_id, validated_at);
CREATE INDEX IF NOT EXISTS idx_announcements_active_dates ON system_announcements (is_active, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_evidences_app_req ON requirements_evidences (application_id, requirement_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (user_id) WHERE is_read = FALSE;
CREATE INDEX IF NOT EXISTS idx_notifications_sent_at ON notifications (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_slas_active_profile ON slas (is_active, target_profile);
CREATE INDEX IF NOT EXISTS idx_badge_apps_opened_at ON badge_applications (opened_at);
CREATE INDEX IF NOT EXISTS idx_sl_lp_id ON service_lines (learning_path_id);
CREATE INDEX IF NOT EXISTS idx_areas_sl_id ON areas (service_line_id);
CREATE INDEX IF NOT EXISTS idx_stages_area_id ON progression_stages (area_id);
CREATE INDEX IF NOT EXISTS idx_evidences_review_status ON requirements_evidences (tm_reviewed, sll_reviewed);
CREATE INDEX IF NOT EXISTS idx_skills_name ON skills (skill_name);
CREATE INDEX IF NOT EXISTS idx_badges_title_trgm ON badges USING gin (badge_title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_users_name_trgm ON users USING gin (full_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_stages_sequence ON progression_stages (area_id, stage_sequence);
CREATE INDEX IF NOT EXISTS idx_requirements_sequence ON badge_requirements (badge_id, requirement_sequence);
CREATE INDEX IF NOT EXISTS idx_tokens_active_user ON user_account_tokens (user_id, token_type) WHERE is_used = FALSE;
CREATE INDEX IF NOT EXISTS idx_users_email_confirmed ON users (email_confirmed) WHERE email_confirmed = FALSE;
CREATE INDEX IF NOT EXISTS idx_badge_apps_guid ON badge_applications (application_guid);
CREATE INDEX IF NOT EXISTS idx_sll_service_line ON service_line_leaders (user_id, service_line_id);
CREATE INDEX IF NOT EXISTS idx_device_tokens_fcm_token ON device_tokens (fcm_token);
CREATE INDEX IF NOT EXISTS idx_device_tokens_user_active ON device_tokens (user_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_user_notif_prefs_user ON user_notification_preferences (user_id);
CREATE INDEX IF NOT EXISTS idx_user_notif_prefs_def ON user_notification_preferences (definition_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON user_refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_account_tokens_value ON user_account_tokens (token_value);

